import csv, unicodedata

def normalize(text):
    ligatures = {
        'œ': 'oe', 'Œ': 'OE', 'æ': 'ae', 'Æ': 'AE',
        'ß': 'ss', 'ð': 'd', 'Ð': 'D', 'þ': 'th', 'Þ': 'TH',
        'ŋ': 'n', 'ı': 'i',
    }
    for src, dst in ligatures.items():
        text = text.replace(src, dst)
    nfkd = unicodedata.normalize('NFKD', text)
    return ''.join(c for c in nfkd if unicodedata.category(c) != 'Mn')

new_phrases = [
    # ═══════════════════════════════════════════════════════
    # ESPAÑOL (es)
    # ═══════════════════════════════════════════════════════
    ("es", "En el principio era el Verbo y el Verbo estaba con Dios"),
    ("es", "La vida es sueño y los sueños sueños son y pronto pasan"),
    ("es", "Poderoso caballero es don Dinero, más que el amor y el honor"),
    ("es", "Yo soy yo y mi circunstancia, y si no la salvo a ella no me salvo"),
    ("es", "El hombre es un lobo para el hombre cuando olvida su humanidad"),
    ("es", "La lengua es el arma más peligrosa que ha inventado el ser humano"),
    ("es", "No hay mal que por bien no venga si se sabe esperar con paciencia"),
    ("es", "Dime con quién andas y te diré quién eres en esta vida"),
    ("es", "Más vale tarde que nunca, dice el sabio refrán de siempre"),
    ("es", "La paciencia es la madre de todas las ciencias y virtudes"),
    ("es", "El amor es el encuentro de dos soledades que se acompañan"),
    ("es", "La esperanza es lo último que se pierde en el corazón humano"),
    ("es", "Quien mucho abarca poco aprieta y al final pierde todo"),
    ("es", "El tiempo es el mejor maestro aunque mata a todos sus alumnos"),
    ("es", "El que a buen árbol se arrima buena sombra le cobija"),
    ("es", "No hay peor sordo que el que no quiere oír la verdad"),
    ("es", "La ignorancia es atrevida y el saber es siempre humilde"),
    ("es", "El saber no ocupa lugar y abre todas las puertas del mundo"),
    ("es", "Quien siembra vientos recoge tempestades, dice el proverbio"),
    ("es", "La amistad verdadera se conoce en los momentos de dificultad"),
    ("es", "El trabajo dignifica al hombre y lo hace dueño de su destino"),
    ("es", "La libertad es el bien más preciado que posee el ser humano"),
    ("es", "El corazón tiene razones que la razón no comprende ni entiende"),
    ("es", "La lectura es el viaje de los que no pueden tomar el tren"),
    ("es", "Más sabe el diablo por viejo que por diablo, dice el pueblo"),
    ("es", "La curiosidad mató al gato pero la satisfacción lo resucitó"),
    ("es", "El hombre propone y Dios dispone con infinita sabiduría"),
    ("es", "La verdad es la hija del tiempo y la madre de la justicia"),
    ("es", "Un pueblo que no conoce su historia está condenado a repetirla"),
    ("es", "La cultura es lo que queda cuando se olvida todo lo aprendido"),
    ("es", "El miedo es el padre de la crueldad y el abuelo de la tiranía"),
    ("es", "La fe mueve montañas cuando es sincera y viene del corazón"),
    ("es", "El silencio es más elocuente que mil palabras juntas"),
    ("es", "La música es el alimento del alma y el remedio del corazón"),
    ("es", "Quien no se aventura no pasa la mar ni gana fortuna alguna"),
    ("es", "La vida es un viaje y cada uno lleva su propio equipaje"),
    ("es", "El arte es la mentira que nos permite conocer la verdad"),
    ("es", "La belleza está en los ojos del que mira con amor y ternura"),
    ("es", "Camarón que se duerme se lo lleva la corriente del río"),
    ("es", "El que ríe último ríe mejor y más satisfecho al final"),
    ("es", "La fortuna ayuda a los audaces que no se detienen ante nada"),
    ("es", "No todo lo que brilla es oro ni toda sonrisa es sincera"),
    ("es", "El árbol se conoce por sus frutos y el hombre por sus actos"),
    ("es", "La memoria es el diario que todos llevamos con nosotros siempre"),
    ("es", "Quien busca con sinceridad y perseverancia siempre encuentra"),
    ("es", "La gratitud es la memoria del corazón y la alegría del alma"),
    ("es", "El hábito hace al monje y el carácter hace al verdadero hombre"),
    ("es", "La creatividad es la inteligencia divirtiéndose con libertad"),
    ("es", "Ojos que no ven, corazón que no siente ni sufre por ello"),
    ("es", "Más vale un pájaro en mano que cien volando por el cielo"),
    ("es", "La verdad duele pero sana; la mentira agrada pero envenena"),
    ("es", "El destino es lo que hacemos con nuestras propias manos"),
    ("es", "Quien tiene un amigo tiene un tesoro que no tiene precio"),
    ("es", "La sabiduría comienza con el asombro ante las cosas simples"),
    ("es", "El futuro pertenece a quienes creen en la belleza de sus sueños"),
    ("es", "La vida no se mide por los años sino por los momentos vividos"),
    ("es", "Ama y haz lo que quieras, porque el amor nunca puede errar"),
    ("es", "El conocimiento es la única riqueza que nadie puede quitarte"),
    ("es", "La alegría está en las pequeñas cosas de la vida cotidiana"),
    ("es", "Quien no arriesga no gana y se queda siempre en el mismo lugar"),
    ("es", "La amistad es un alma que habita en dos cuerpos diferentes"),
    ("es", "El mundo es un libro y quien no viaja solo lee una página"),
    ("es", "La razón es la sirvienta del corazón y no su amo y señor"),
    ("es", "Vivir sin filosofar es tener los ojos a medias cerrados"),
    ("es", "El coraje no es la ausencia del miedo sino la victoria sobre él"),
    ("es", "La poesía es la voz secreta del universo que canta en nosotros"),
    ("es", "Quien bien te quiere te hará llorar, dice el refrán antiguo"),
    ("es", "La noche es el consejero y la mañana la claridad y la acción"),
    ("es", "El hombre es la medida de todas las cosas, dijo el filósofo"),
    ("es", "La ciencia sin conciencia es la ruina del alma y del espíritu"),
    ("es", "No hay camino para la paz, la paz es el único camino posible"),
    ("es", "El amor verdadero empieza cuando nada se espera a cambio"),
    ("es", "La generosidad no se mide por lo que das sino por lo que guardas"),
    ("es", "Un libro cerrado es un amigo que espera pacientemente tu llamada"),
    ("es", "La imaginación es el ojo del alma que todo puede ver y crear"),
    ("es", "El que madruga Dios le ayuda y el sol le da los buenos días"),
    ("es", "Perdonar es liberar a un prisionero y descubrir que eras tú"),
    ("es", "La humildad es la madre de las virtudes y la hija de la sabiduría"),
    ("es", "Aprende del ayer, vive el hoy y espera el mañana con esperanza"),
    ("es", "La lengua no tiene huesos pero rompe huesos y destroza corazones"),
    ("es", "El optimista ve una oportunidad en cada dificultad que encuentra"),
    ("es", "La soledad es el precio que paga el genio por su grandeza interior"),
    ("es", "El amor es un fuego que arde sin que nadie pueda verlo"),
    ("es", "La palabra dada es una flecha disparada que no vuelve jamás"),
    ("es", "Quien mucho duerme poco aprende y menos aún consigue en la vida"),
    ("es", "La honradez es la mejor política en todos los tiempos y lugares"),
    ("es", "El placer de leer es el más económico de todos los lujos posibles"),
    ("es", "La paciencia es amarga pero su fruto es dulce y merece la pena"),
    ("es", "Nada es imposible para quien lo intenta con fe y perseverancia"),
    ("es", "El sabio no dice todo lo que piensa pero piensa todo lo que dice"),
    ("es", "La vida es bella cuando se ama y uno se siente amado de verdad"),
    ("es", "Todo lo que empieza bien tiene posibilidades de terminar bien"),
    ("es", "El éxito no es definitivo, el fracaso no es fatal, el valor sí"),
    ("es", "La costumbre es una segunda naturaleza que nos moldea sin saberlo"),
    ("es", "Quien a hierro mata a hierro muere, dice la justicia eterna"),
    ("es", "La risa es el sol que ahuyenta el invierno del rostro humano"),
    ("es", "El pasado no se puede cambiar, el futuro aún está en tus manos"),
    ("es", "La simplicidad es la sofisticación suprema del verdadero genio"),
    ("es", "Con paciencia y saliva el elefante se comió a la hormiguita"),
    ("es", "El que no llora no mama y el que no se mueve no prospera"),
    ("es", "La belleza sin bondad es una flor sin perfume y sin raíces"),
    ("es", "No hay enemigo pequeño ni herida leve cuando duele el corazón"),
    ("es", "El amor es ciego pero el matrimonio le devuelve la vista pronto"),
    ("es", "La muerte no es nada, pero vivir vencido es morir cada día"),
    ("es", "Quien todo lo quiere todo lo pierde y acaba con las manos vacías"),
    ("es", "La historia es una galería donde hay pocos cuadros originales"),
    ("es", "El mundo está en manos de quienes tienen el coraje de soñar"),
    ("es", "La guerra es la continuación de la política por otros medios"),
    ("es", "No basta saber, se debe también aplicar lo que uno ha aprendido"),
    ("es", "El genio es un uno por ciento de inspiración y el resto sudor"),
    ("es", "La voluntad es el músculo más poderoso del cuerpo y del alma"),
    ("es", "Un pueblo educado es un pueblo libre y dueño de su destino"),
    ("es", "El que no trabaja no come y el que no siembra no recoge frutos"),
    ("es", "La envidia es la admiración de los tontos hacia los inteligentes"),
    ("es", "Cada uno es hijo de sus obras y arquitecto de su propia vida"),
    ("es", "La locura es hacer lo mismo una y otra vez esperando resultados distintos"),
    ("es", "El amor de madre no tiene precio ni sustituto en este mundo"),
    ("es", "Quien no conoce la historia está condenado a repetir sus errores"),
    ("es", "La fe es creer en lo que no se ve y la recompensa ver lo que se cree"),
    ("es", "El camino al infierno está empedrado de buenas intenciones"),
    ("es", "La esperanza es el sueño de un hombre despierto que no rinde"),
    ("es", "No hay rosa sin espinas ni triunfo sin sacrificio y esfuerzo"),
    ("es", "El que busca la verdad merece los golpes de quien la defiende"),
    ("es", "La juventud es una enfermedad de la que se cura con el tiempo"),
    ("es", "El orgullo es la máscara del débil y el escudo del cobarde"),
    ("es", "La naturaleza no da saltos sino que va paso a paso siempre"),
    ("es", "Quien habla mucho yerra mucho y pocas veces dice algo importante"),
    ("es", "La tristeza compartida es una tristeza reducida a la mitad"),
    ("es", "El honor es como la honra del vidrio, que no admite reparación"),
    ("es", "No hay viento favorable para el marinero que no sabe adónde ir"),
    ("es", "La confianza en uno mismo es el secreto del primer paso al éxito"),
    ("es", "El justo medio es la virtud perfecta que recomienda el sabio"),
    ("es", "Donde hay amor hay vida y donde hay vida hay esperanza siempre"),
    ("es", "La experiencia es el nombre que cada uno da a sus propios errores"),
    ("es", "No hay mal que dure cien años ni cuerpo que lo resista al fin"),
    ("es", "La educación es el arma más poderosa para cambiar el mundo"),
    ("es", "El sol sale para todos sin distinción de riqueza ni de rango"),
    ("es", "Más vale prevenir que curar cuando aún hay tiempo para hacerlo"),
    ("es", "La voluntad mueve montañas cuando es firme y verdadera en el alma"),
    ("es", "No se puede hacer una tortilla sin romper los huevos primero"),
    ("es", "El amor es la única locura de la que nadie quiere curarse jamás"),
    ("es", "La grandeza de un hombre se mide por lo que hace por los demás"),
    ("es", "Piensa mal y acertarás a veces, aunque no siempre es así"),
    ("es", "La inspiración existe pero tiene que encontrarte trabajando duro"),
    ("es", "El respeto se gana, la honestidad se aprecia, la fe se cultiva"),
    ("es", "Quien tiene salud tiene esperanza y quien tiene esperanza lo tiene todo"),
    ("es", "La libertad de uno termina donde comienza la libertad del otro"),
    ("es", "El tiempo perdido no vuelve y la juventud no espera ni perdona"),
    ("es", "No hay atajo que no tenga su trabajo y su propio precio final"),
    ("es", "La vida es lo que nos pasa mientras hacemos otros planes futuros"),
    ("es", "El conocimiento sin sabiduría es una espada en manos de un niño"),
    ("es", "Quien no agradece lo poco no merece recibir lo mucho tampoco"),
    ("es", "La creatividad nace del deseo de explorar lo que está más allá"),
    ("es", "Un corazón agradecido es el jardín más bello de todos los que existen"),
    ("es", "El que no sabe es como el que no ve aunque tenga ojos abiertos"),
    ("es", "La moderación en todo es el secreto de una vida larga y feliz"),
    ("es", "No hay mejor espejo que el amigo antiguo que te conoce bien"),
    ("es", "El trabajo bien hecho es la única respuesta que importa al fin"),
    ("es", "La belleza del alma supera con creces a la belleza del cuerpo"),
    ("es", "Quien siembra con lágrimas recoge con alegría y abundancia"),
    ("es", "El corazón del hombre es insondable y guarda sus propios secretos"),
    ("es", "La paz del alma vale más que todos los tesoros del mundo entero"),
    ("es", "No hay peor ciego que el que no quiere ver lo que está delante"),
    ("es", "El camino de mil millas comienza siempre con un solo paso firme"),
    ("es", "La palabra amable no cuesta nada y vale muchísimo a quien la recibe"),
    ("es", "Quien da pan a perro ajeno pierde el pan y pierde el perro"),
    ("es", "La perseverancia es el camino del triunfo para quien no se rinde"),
    ("es", "El noble de espíritu es independiente del noble de sangre y cuna"),
    ("es", "No te rindas que la vida es eso, continuar el viaje y crecer"),
    ("es", "La historia no se repite pero a veces rima con sorprendente exactitud"),
    ("es", "El ignorante afirma, el sabio duda y el inteligente reflexiona"),
    ("es", "La bondad es la única riqueza que no puede robarnos nadie jamás"),
    ("es", "Quien planta un árbol ama a los demás más que a sí mismo"),
    ("es", "La nobleza obliga y quien la tiene debe merecerla cada día"),
    ("es", "El que pregunta no yerra y el que escucha aprende sin cesar"),
    ("es", "La democracia es el peor sistema excepto todos los demás conocidos"),
    ("es", "No hay secreto que no se sepa ni verdad que no acabe saliendo"),
    ("es", "El carácter se forma en la tormenta y no en la calma tranquila"),
    ("es", "La gratitud convierte lo que tenemos en suficiente para ser felices"),
    ("es", "Quien no tiene memoria no tiene historia ni futuro ni identidad"),
    ("es", "La dignidad no consiste en tener honores sino en merecerlos bien"),
    ("es", "El arte de vivir es sacrificar lo que se quiere por lo que se desea"),
    ("es", "No basta con querer ser bueno, hay que serlo todos los días"),
    ("es", "La valentía es resistir al miedo y dominar el miedo, no ausencia"),
    ("es", "Quien todo lo quiere para sí mismo lo pierde todo en un momento"),
    ("es", "La constancia es la virtud por la cual todas las otras virtudes dan fruto"),
    ("es", "El amor propio es el fundamento de todo amor verdadero hacia otro"),
    ("es", "No hay camino fácil desde la tierra hasta las estrellas del cielo"),
    ("es", "La alegría compartida es alegría doblada; dolor compartido, reducido"),
    ("es", "Quien tiene el por qué para vivir soporta casi cualquier cómo"),
    ("es", "El pasado es un prólogo y el futuro es la historia que aún no escribimos"),
    ("es", "La mente es como un paracaídas: solo funciona cuando está abierta"),
    ("es", "No hay mayor riqueza que la salud del cuerpo y la paz del alma"),
    ("es", "El amor y la razón no van de la mano pero se necesitan el uno al otro"),
    ("es", "La ambición sin talento es un árbol sin frutos ni sombra alguna"),
    ("es", "Quien nace para martillo del cielo le caen los clavos siempre"),
    ("es", "La verdad es simple y las mentiras son siempre complicadas y largas"),
    ("es", "El mejor momento para plantar un árbol fue hace veinte años"),
    ("es", "La sabiduría popular es la filosofía de los que han vivido mucho"),
    ("es", "Quien bien ama tarde olvida y quien olvida pronto nunca amó bien"),
    ("es", "La razón sin sentimiento es fría como el mármol de una tumba"),
    ("es", "El hábito no hace al monje pero ayuda mucho a parecerlo bien"),
    ("es", "No hay enemigo más temible que el amigo que se vuelve en contra"),
    ("es", "La juventud es una borrachera sin vino y la vejez un vino sin borrachera"),
    ("es", "Quien no sabe callar no sabe hablar y hace daño sin quererlo"),
    ("es", "La ambición es la última enfermedad de los espíritus nobles y elevados"),
    ("es", "El tiempo cura las heridas que la razón no es capaz de sanar sola"),
    ("es", "No hay victoria sin sacrificio ni gloria sin esfuerzo y constancia"),
    ("es", "La cortesía es la flor de la humanidad y el perfume de la civilización"),
    ("es", "Quien ama el peligro en él perece, dice la sabiduría antigua"),
    ("es", "La riqueza no da la felicidad pero ayuda a comprarla a veces"),
    ("es", "El que no llora en su niñez llora en su vejez sin remedio"),
    ("es", "La disciplina es el puente entre las metas y los logros reales"),
    ("es", "No hay que confundir el movimiento con el progreso real y duradero"),
    ("es", "El verdadero viaje de descubrimiento no es buscar tierras nuevas"),
    ("es", "La enemistad entre sabios es mejor que la amistad entre necios"),
    ("es", "Quien sabe esperar obtiene lo que quiere con menos esfuerzo"),
    ("es", "La duda es el principio de la sabiduría, dijo el filósofo griego"),
    ("es", "El que guarda siempre halla y el que busca siempre encuentra algo"),
    ("es", "La fuerza del carácter se revela en la tempestad y el adversidad"),
    ("es", "No hay cosa imposible para quien tiene voluntad firme y coraje"),
    ("es", "El sabio no es el que más sabe sino el que mejor usa lo que sabe"),
    ("es", "La igualdad de trato es la base de toda convivencia civilizada"),
    ("es", "Quien vive sin disciplina muere sin honor y sin logro alguno"),
    ("es", "La amistad duplica las alegrías y divide las angustias por mitad"),
    ("es", "El miedo a equivocarse es el mayor obstáculo para aprender algo nuevo"),
    ("es", "La imaginación es más importante que el conocimiento acumulado"),
    ("es", "No hay mejor maestro que el que enseña con el ejemplo propio"),
    ("es", "El límite de tu lenguaje es el límite de tu mundo y tu universo"),
    ("es", "La familia es el primer país que habitamos antes que cualquier otro"),
    ("es", "Quien planta bondad cosecha amistad duradera y paz interior"),
    ("es", "La luz no se puede esconder por mucho tiempo debajo de un cajón"),
    ("es", "El que no agradece lo pequeño no merece lo grande que está por venir"),
    ("es", "La ciencia es la religión de los que creen en la razón y la evidencia"),
    ("es", "No hay mal tan grande que no se pueda convertir en bien con esfuerzo"),

    # ═══════════════════════════════════════════════════════
    # ENGLISH (en)
    # ═══════════════════════════════════════════════════════
    ("en", "To be or not to be, that is the question for every mortal soul"),
    ("en", "All that glitters is not gold and not every smile is sincere"),
    ("en", "The course of true love never did run smooth in any age"),
    ("en", "We know what we are but know not what we may become"),
    ("en", "What a piece of work is man, how noble in reason and faculty"),
    ("en", "There is nothing either good or bad but thinking makes it so"),
    ("en", "This above all: to thine own self be true, and follow your heart"),
    ("en", "The quality of mercy is not strained; it droppeth as gentle rain"),
    ("en", "All the world is a stage and all the men and women merely players"),
    ("en", "We are such stuff as dreams are made on, and our life is rounded"),
    ("en", "Give every man thine ear but few thy voice and fewer thy trust"),
    ("en", "Brevity is the soul of wit and length the body of tedium always"),
    ("en", "One touch of nature makes the whole world kin and brothers"),
    ("en", "How sharper than a serpent's tooth it is to have a thankless child"),
    ("en", "The lady doth protest too much, methinks, about her innocence"),
    ("en", "Good night, good night, parting is such sweet sorrow to us all"),
    ("en", "What's in a name? That which we call a rose by any other name"),
    ("en", "I am not bound to please thee with my answers given freely"),
    ("en", "The better part of valour is discretion in the face of danger"),
    ("en", "Hell is empty and all the devils are here among us now"),
    ("en", "It is not in the stars to hold our destiny but in ourselves"),
    ("en", "Cowards die many times before their deaths and feel each one"),
    ("en", "The evil that men do lives after them; the good is interred"),
    ("en", "Friends, Romans, countrymen, lend me your ears and your hearts"),
    ("en", "Et tu, Brute? Then fall, Caesar, and let the world remember"),
    ("en", "The fault, dear Brutus, is not in our stars but in ourselves"),
    ("en", "How beautiful is night when love is in the air all around"),
    ("en", "There is no darkness but ignorance to keep a man from his path"),
    ("en", "Be not afraid of greatness; some are born great, some achieve"),
    ("en", "In the beginning was the Word and the Word was full of light"),
    ("en", "Ask not what your country can do for you, ask what you can do"),
    ("en", "That is one small step for a man, one giant leap for mankind"),
    ("en", "I have a dream that one day this nation will rise and be free"),
    ("en", "The only thing we have to fear is fear itself standing before us"),
    ("en", "Give me liberty or give me death, for I will not live as a slave"),
    ("en", "We hold these truths to be self-evident, that all men are equal"),
    ("en", "Four score and seven years ago our fathers brought forth a nation"),
    ("en", "In the middle of difficulty lies opportunity waiting to be found"),
    ("en", "Try not to become a man of success but rather a man of value"),
    ("en", "Imagination is more important than knowledge in every endeavor"),
    ("en", "The measure of intelligence is the ability to change and adapt"),
    ("en", "Life is like riding a bicycle; to keep balance you must keep moving"),
    ("en", "Not everything that counts can be counted and vice versa"),
    ("en", "Education is what remains after one has forgotten what was learned"),
    ("en", "Two things are infinite: the universe and human stupidity"),
    ("en", "Reality is merely an illusion, albeit a very persistent one"),
    ("en", "The world as we have created it is a process of our thinking"),
    ("en", "Weakness of attitude becomes weakness of character over time"),
    ("en", "A person who never made a mistake never tried anything new"),
    ("en", "The important thing is not to stop questioning and wondering"),
    ("en", "It has become appallingly obvious that our technology has exceeded"),
    ("en", "Pure mathematics is, in its way, the poetry of logical ideas"),
    ("en", "If you can't explain it simply, you don't understand it well"),
    ("en", "Any intelligent fool can make things bigger and more complex"),
    ("en", "The only source of knowledge is experience gained in living"),
    ("en", "The secret of getting ahead is getting started right now today"),
    ("en", "You miss one hundred percent of the shots you don't ever take"),
    ("en", "Whether you think you can or you can't, you are always right"),
    ("en", "It always seems impossible until it's actually been done fully"),
    ("en", "The greatest glory in living lies not in never falling but rising"),
    ("en", "Education is the most powerful weapon you can use to change things"),
    ("en", "Do not judge me by my successes, judge me by how many times I fell"),
    ("en", "I never lose; I either win or I learn something valuable"),
    ("en", "It does not matter how slowly you go as long as you never stop"),
    ("en", "Our greatest weakness lies in giving up and taking the easy path"),
    ("en", "The way to get started is to quit talking and begin doing it now"),
    ("en", "Don't let yesterday take up too much of today's precious time"),
    ("en", "You learn more from failure than from success in the end"),
    ("en", "If you are working on something exciting, it will keep you going"),
    ("en", "We may encounter many defeats but we must not be defeated by them"),
    ("en", "Knowing is not enough; we must apply what we know to life"),
    ("en", "Honesty is the first chapter in the book of true wisdom"),
    ("en", "Nothing in life is to be feared, it is only to be understood"),
    ("en", "Science knows no country because knowledge belongs to humanity"),
    ("en", "The best way to predict the future is to invent it yourself"),
    ("en", "One good head is better than a hundred strong hands alone"),
    ("en", "The more you know the more you realize you do not know"),
    ("en", "Research is to see what everybody has seen and think differently"),
    ("en", "No great discovery was ever made without a bold guess first"),
    ("en", "Truth in science can be defined as the working hypothesis"),
    ("en", "The beginning of wisdom is the definition of terms for thinking"),
    ("en", "Pleasure in the job puts perfection in the work done well"),
    ("en", "We are what we repeatedly do; excellence is not an act but habit"),
    ("en", "The roots of education are bitter but the fruit is always sweet"),
    ("en", "Man by nature desires to know and seeks knowledge everywhere"),
    ("en", "To know oneself is the beginning of all true wisdom and virtue"),
    ("en", "It is the mark of an educated mind to entertain a thought"),
    ("en", "Quality is not an act, it is a habit formed over long time"),
    ("en", "The whole is more than the sum of its parts taken separately"),
    ("en", "Friendship is essentially a partnership between like-minded souls"),
    ("en", "Hope is a waking dream that never fully leaves us while we live"),
    ("en", "Beauty is the gift of the gods to those who can perceive it"),
    ("en", "Love is composed of a single soul inhabiting two separate bodies"),
    ("en", "The energy of the mind is the essence of all true human life"),
    ("en", "Happiness depends upon ourselves and the choices that we make"),
    ("en", "In all things of nature there is something of the marvelous"),
    ("en", "The educated differ from the uneducated as much as the living"),
    ("en", "He who has overcome his fears will truly be free at last"),
    ("en", "Well begun is half done, as the ancient saying tells us always"),
    ("en", "The aim of art is to represent not the outward but the inward"),
    ("en", "No great mind has ever existed without a touch of madness"),
    ("en", "Count your age by friends, not years, and not by wins or losses"),
    ("en", "Yesterday is history, tomorrow is mystery, today is a gift"),
    ("en", "Be yourself; everyone else is already taken and spoken for"),
    ("en", "We are all in the gutter but some of us are looking at the stars"),
    ("en", "The truth is rarely pure and never simple in this world"),
    ("en", "Experience is the name everyone gives to their own mistakes"),
    ("en", "I can resist everything except temptation placed before me"),
    ("en", "To live is the rarest thing in the world; most people just exist"),
    ("en", "A man who does not think for himself does not think at all"),
    ("en", "Always forgive your enemies, nothing annoys them so much"),
    ("en", "Every saint has a past and every sinner has a future ahead"),
    ("en", "I am so clever that sometimes I don't understand a single word"),
    ("en", "What seems to us as bitter trials are often blessings in disguise"),
    ("en", "With freedom, flowers, books and the moon who could not be happy"),
    ("en", "You can never be overdressed or overeducated in this life"),
    ("en", "The only way to get rid of a temptation is to yield to it"),
    ("en", "A good friend will always stab you in the front, never the back"),
    ("en", "The books that the world calls immoral are books that show its shame"),
    ("en", "I don't want to earn my living; I want to live and fully breathe"),
    ("en", "The very essence of romance is uncertainty and the unknown"),
    ("en", "A dreamer is one who can only find his way by moonlight"),
    ("en", "The aim of life is self-development and the realization of nature"),
    ("en", "Most people are other people, full of other people's opinions"),
    ("en", "Selfishness is not living as one wishes to live, it is asking others"),
    ("en", "It is not the strongest species that survive nor the most intelligent"),
    ("en", "In the long history of humankind those who learned to cooperate"),
    ("en", "A man's worth is no greater than the worth of his ambitions"),
    ("en", "I have never let schooling interfere with my education ever"),
    ("en", "The secret of getting ahead is getting started before you're ready"),
    ("en", "Whenever you find yourself on the side of the majority, pause"),
    ("en", "Truth is stranger than fiction but fiction is more comfortable"),
    ("en", "The man who does not read has no advantage over the man who cannot"),
    ("en", "Age is an issue of mind over matter; if you don't mind, it doesn't"),
    ("en", "Courage is resistance to fear, mastery of fear, not absence of it"),
    ("en", "Give a man a fish and you feed him for a day; teach him to fish"),
    ("en", "Not all those who wander are lost; some are finding their way"),
    ("en", "All that is gold does not glitter, not all those who wander are lost"),
    ("en", "A single dream is more powerful than a thousand realities we know"),
    ("en", "Little by little, one travels far and arrives at the destination"),
    ("en", "Deep roots are not reached by the frost and will survive all things"),
    ("en", "The world is full of obvious things which nobody by chance ever"),
    ("en", "It is a truth universally acknowledged that man seeks to be happy"),
    ("en", "There is no charm equal to tenderness of heart in any person"),
    ("en", "A large income is the best recipe for happiness I ever heard of"),
    ("en", "I declare after all there is no enjoyment like reading a good book"),
    ("en", "It is not what we say or think that defines us but what we do"),
    ("en", "Vanity and pride are different things though the words are often used"),
    ("en", "Till this moment I never knew myself and what I truly wanted"),
    ("en", "There is no love like a mother's, and no friend like a sister"),
    ("en", "Happiness in marriage is entirely a matter of chance and chemistry"),
    ("en", "An unhappy alternative is before you, Elizabeth; your duty now"),
    ("en", "My courage always rises at every attempt to intimidate me"),
    ("en", "I am determined that nothing but the deepest love shall induce me"),
    ("en", "Think only of the past as its remembrance gives you pleasure"),
    ("en", "We are all fools in love, that much is universally accepted"),
    ("en", "One cannot think well, love well, sleep well without having eaten"),
    ("en", "The older I get, the more wisdom I find in the ancient rule"),
    ("en", "On the day you were born you began to die; do not waste a moment"),
    ("en", "He who is brave is free, even in chains, even in slavery"),
    ("en", "Luck is what happens when preparation meets real opportunity"),
    ("en", "If you wish to be loved, show more of your faults than virtues"),
    ("en", "We suffer more in imagination than in reality, said the stoic"),
    ("en", "Begin at once to live and count each separate day as a life"),
    ("en", "The best revenge is not to be like your enemy in any respect"),
    ("en", "If you want to be happy, be and stop looking for reasons not to"),
    ("en", "No man is free who is not master of himself and his reactions"),
    ("en", "Difficulties strengthen the mind as labor does the body over time"),
    ("en", "True happiness is to enjoy the present without anxious dependence"),
    ("en", "Associate with those who will make a better person of you always"),
    ("en", "A gem cannot be polished without friction nor man without trials"),
    ("en", "The more we sweat in peace the less we bleed in war and conflict"),
    ("en", "It is not that I'm so smart, it's just that I stay with problems"),
    ("en", "Insanity is doing the same thing and expecting different results"),
    ("en", "There are only two ways to live your life, one is as if nothing"),
    ("en", "Logic will get you from A to B; imagination will take you everywhere"),
    ("en", "The world is not dangerous because of those who do harm to others"),
    ("en", "Strive not to be a success but rather to be of value to others"),
    ("en", "A happy man is too satisfied with the present to dwell on future"),
    ("en", "Peace cannot be kept by force; it can only be achieved by understanding"),
    ("en", "The true sign of intelligence is not knowledge but imagination"),
    ("en", "When you are a Bear of Very Little Brain, big words bother you"),
    ("en", "You can't stay in your corner of the Forest waiting for others"),
    ("en", "Promise me you'll always remember that you are braver than you believe"),
    ("en", "Rivers know this: there is no hurry; we shall get there some day"),
    ("en", "A little consideration, a little thought for others makes all the diff"),
    ("en", "Some people care too much, I think it is called love in the end"),
    ("en", "If there ever comes a day when we can't be together keep me in heart"),
    ("en", "The things that make me different are the things that make me who I am"),
    ("en", "How lucky I am to have something that makes saying goodbye so hard"),
    ("en", "You are braver than you believe and stronger than you seem today"),
    ("en", "To the well-organized mind death is but the next great adventure"),
    ("en", "Words are, in my not so humble opinion, our most inexhaustible magic"),
    ("en", "It matters not what someone is born but what they grow to become"),
    ("en", "Happiness can be found even in the darkest of times if one remembers"),
    ("en", "It is our choices that show what we truly are far more than abilities"),
    ("en", "Fear of a name increases fear of the thing itself, said the wise one"),
    ("en", "Do not pity the dead; pity the living, and above all those who live"),
    ("en", "It takes a great deal of bravery to stand up to our enemies, yes"),
    ("en", "No story lives unless someone wants to listen to it being told"),
    ("en", "We are only as strong as we are united, as weak as we are divided"),
    ("en", "Not all treasure is silver and gold, mate, some of it is invisible"),
    ("en", "The problem is not the problem; the problem is your attitude"),
    ("en", "Better to remain silent and be thought a fool than to speak and confirm"),
    ("en", "Nearly all men can stand adversity, but if you want to test a man"),
    ("en", "Give me six hours to chop down a tree and I will spend four sharpening"),
    ("en", "Whatever you are, be a good one and do your best every day"),
    ("en", "The best thing about the future is that it comes one day at a time"),
    ("en", "I walk slowly but I never walk backward; I always go forward"),
    ("en", "No matter how much cats fight there always seem to be kittens"),
    ("en", "Character is like a tree and reputation like a shadow it casts"),
    ("en", "I am a slow walker but I never walk back; I persist in my path"),
    ("en", "You can fool all the people some of the time and that may suffice"),
    ("en", "A house divided against itself cannot stand and will surely fall"),
    ("en", "The philosophy of the school room in one generation will be next"),
    ("en", "Things may come to those who wait but only what is left by those"),
    ("en", "When you reach the end of your rope, tie a knot in it and hang on"),
    ("en", "Most folks are about as happy as they make up their minds to be"),
    ("en", "Leave nothing for tomorrow which can be done today with full heart"),
]

# Normalizar
def normalize(text):
    ligatures = {
        'œ': 'oe', 'Œ': 'OE', 'æ': 'ae', 'Æ': 'AE',
        'ß': 'ss', 'ð': 'd', 'Ð': 'D', 'þ': 'th', 'Þ': 'TH',
        'ŋ': 'n', 'ı': 'i',
    }
    for src, dst in ligatures.items():
        text = text.replace(src, dst)
    nfkd = unicodedata.normalize('NFKD', text)
    return ''.join(c for c in nfkd if unicodedata.category(c) != 'Mn')

# Filtrar 50-100 chars y deduplicar
path = r'C:\Users\nicoa\romance_dataset.csv'
with open(path, encoding='utf-8') as f:
    existing = list(csv.DictReader(f))

existing_texts = {r['text'] for r in existing}
max_id = max(int(r['id']) for r in existing)

filtered = []
seen = set(existing_texts)
for lang, text in new_phrases:
    t = text.strip()
    if 50 <= len(t) <= 100 and t not in seen:
        seen.add(t)
        filtered.append((lang, t))

print(f"Nuevas frases validas (50-100 chars, sin duplicados): {len(filtered)}")

# Tomar exactamente las que necesitamos para llegar a 1000
needed = 1000 - len(existing)
final_new = filtered[:needed]
print(f"Agregando: {len(final_new)} frases (necesarias para llegar a 1000)")

# Escribir CSV actualizado
all_rows = existing.copy()
for i, (lang, text) in enumerate(final_new, max_id + 1):
    all_rows.append({
        'id': i,
        'language': lang,
        'text': text,
        'text_normalized': normalize(text),
        'char_count': len(text),
    })

with open(path, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(
        f,
        fieldnames=['id', 'language', 'text', 'text_normalized', 'char_count'],
        quoting=csv.QUOTE_ALL
    )
    writer.writeheader()
    writer.writerows(all_rows)

# Estadísticas finales
from collections import Counter
with open(path, encoding='utf-8') as f:
    final = list(csv.DictReader(f))

lang_counts = Counter(r['language'] for r in final)
lengths = [int(r['char_count']) for r in final]
print(f"\nTotal entradas: {len(final)}")
print(f"Chars: min={min(lengths)}, max={max(lengths)}, avg={sum(lengths)/len(lengths):.1f}")
print("\nDistribucion por idioma:")
for lang, count in sorted(lang_counts.items()):
    print(f"  {lang}: {count}")
