import csv, unicodedata
from collections import Counter

def normalize(text):
    ligatures = {
        'œ': 'oe', 'Œ': 'OE', 'æ': 'ae', 'Æ': 'AE',
        'ß': 'ss', 'ð': 'd', 'Ð': 'D', 'þ': 'th', 'Þ': 'TH',
        'ŋ': 'n', 'ı': 'i',
    }
    for src, dst in ligatures.items():
        text = text.replace(src, dst)
    nfkd = unicodedata.normalize('NFKD', text)
    return ''.join(c for c in nfkd if unicodedata.category(c) != 'Mn')

new_phrases = [
    # ═══════════════════════════════════════════════════════
    # FRANÇAIS (fr)
    # ═══════════════════════════════════════════════════════
    ("fr", "La vie n'est qu'une ombre qui passe et un songe fugitif"),
    ("fr", "On ne fait pas d'omelette sans casser des œufs, dit-on"),
    ("fr", "Mieux vaut prévenir que guérir, dit le médecin prudent"),
    ("fr", "À cœur vaillant rien d'impossible sous le soleil ardent"),
    ("fr", "L'avenir appartient à ceux qui se lèvent tôt le matin"),
    ("fr", "Qui veut voyager loin ménage sa monture avec soin"),
    ("fr", "Les absents ont toujours tort dans les querelles humaines"),
    ("fr", "Après la pluie le beau temps revient toujours sur la terre"),
    ("fr", "Trop de précipitation nuit à la perfection de l'œuvre"),
    ("fr", "La nuit tous les chats sont gris et les différences s'effacent"),
    ("fr", "Il ne faut pas vendre la peau de l'ours avant de l'avoir"),
    ("fr", "Paris vaut bien une messe, dit-on depuis Henri Quatre"),
    ("fr", "Il n'est pire eau que l'eau qui dort sous une surface calme"),
    ("fr", "Chassez le naturel il revient au galop sans jamais partir"),
    ("fr", "L'habit ne fait pas le moine mais le représente aux yeux"),
    ("fr", "Loin des yeux loin du cœur mais jamais loin du souvenir"),
    ("fr", "Il vaut mieux avoir la paix que d'avoir raison tout le temps"),
    ("fr", "La bonne conscience est le meilleur oreiller pour dormir"),
    ("fr", "On reconnaît ses amis dans le malheur et non dans le bonheur"),
    ("fr", "L'excès en tout est un défaut que le sage doit éviter"),
    ("fr", "La fortune sourit aux braves et tourne le dos aux timides"),
    ("fr", "Le malheur des uns fait le bonheur des autres en ce monde"),
    ("fr", "Qui ne tente rien n'a rien et ne mérite rien d'autre"),
    ("fr", "La parole est d'argent mais le silence est souvent d'or"),
    ("fr", "Il n'est jamais trop tard pour bien faire ce qu'on remet"),
    ("fr", "Tout ce qui brille n'est pas or ni tout sourire sincère"),
    ("fr", "La vérité sort de la bouche des enfants et des sages"),
    ("fr", "On n'attrape pas les mouches avec du vinaigre mais du miel"),
    ("fr", "Les murs ont des oreilles et les nuits ont des yeux ouverts"),
    ("fr", "Hâtez-vous lentement et sans perdre courage pour arriver"),
    ("fr", "La raison du plus fort est toujours la meilleure, hélas"),
    ("fr", "L'eau qui dort est souvent plus dangereuse que les rapides"),
    ("fr", "Les grandes douleurs sont muettes et ne cherchent pas l'écho"),
    ("fr", "La confiance est la colle qui tient ensemble les relations"),
    ("fr", "Un tiens vaut mieux que deux tu l'auras, dit la sagesse"),
    ("fr", "L'argent ne fait pas le bonheur mais il y contribue un peu"),
    ("fr", "Chaque jour suffit sa peine et chaque heure son propre fardeau"),
    ("fr", "La vérité blesse mais elle guérit plus sûrement que le mensonge"),
    ("fr", "Le mieux est l'ennemi du bien quand on cherche la perfection"),
    ("fr", "Qui court deux lièvres à la fois n'en prend aucun au final"),
    ("fr", "Il faut rendre à César ce qui appartient à César sans hésiter"),
    ("fr", "La jalousie est la sœur de l'amour comme le diable est de Dieu"),
    ("fr", "Le temps perdu ne se retrouve jamais dans aucune boutique"),
    ("fr", "On ne peut pas plaire à tout le monde et à son père en même temps"),
    ("fr", "La beauté intérieure est la seule qui ne vieillisse jamais"),
    ("fr", "Qui aime bien châtie bien, dit le proverbe des grands-mères"),
    ("fr", "Le sage apprend de l'expérience d'autrui et l'idiot de la sienne"),
    ("fr", "La douleur passe mais la beauté que l'on a créée demeure"),
    ("fr", "Mieux vaut une bonne retraite qu'une mauvaise bataille perdue"),
    ("fr", "L'orgueil va devant la ruine et l'esprit hautain avant la chute"),
    ("fr", "Qui dort dîne car le sommeil nourrit le corps et l'âme"),
    ("fr", "La réputation est comme un verre, facile à briser impossible"),
    ("fr", "Il n'y a pas de honte à apprendre de ses propres erreurs passées"),
    ("fr", "La jeunesse est heureuse parce qu'elle a la capacité de voir la beauté"),
    ("fr", "On ne peut pas être et avoir été au même moment dans le temps"),
    ("fr", "Toute médaille a son revers et tout avantage son inconvénient"),
    ("fr", "La persévérance est la clé qui ouvre toutes les portes fermées"),
    ("fr", "Le bonheur n'est pas une destination mais une façon de voyager"),
    ("fr", "La gratitude est le plus beau des sentiments que l'on puisse éprouver"),
    ("fr", "Qui rit vendredi dimanche pleurera, dit le sage populaire"),
    ("fr", "On n'est jamais mieux servi que par soi-même dans ce bas monde"),
    ("fr", "La liberté des uns s'arrête là où commence celle des autres"),
    ("fr", "Il faut tourner sa langue sept fois avant de parler trop vite"),
    ("fr", "Le travail est la source de toutes les richesses et vertus"),
    ("fr", "La modestie est la vertu de ceux qui n'ont rien à cacher"),
    ("fr", "Qui sème la discorde récolte la haine et la solitude amère"),
    ("fr", "La passion sans raison est un feu qui consume sans éclairer"),
    ("fr", "L'art de vivre c'est l'art de savoir sacrifier le superflu"),
    ("fr", "Le courage est la première des vertus car elle les rend possibles"),
    ("fr", "La prudence est la mère de la sûreté et la fille de l'expérience"),
    ("fr", "Nul ne peut servir deux maîtres à la fois sans trahir l'un"),

    # ═══════════════════════════════════════════════════════
    # ITALIANO (it)
    # ═══════════════════════════════════════════════════════
    ("it", "Meglio tardi che mai, dice il vecchio proverbio della nonna"),
    ("it", "La vita è bella quando si vive con passione e determinazione"),
    ("it", "Chi ben comincia ha già fatto la metà del lavoro difficile"),
    ("it", "L'amore non si chiede, si dà senza calcolo e senza misura"),
    ("it", "Non rimandare a domani quello che puoi fare oggi con gioia"),
    ("it", "Chi trova un amico trova un tesoro che dura tutta la vita"),
    ("it", "Il sole splende per tutti senza fare distinzione di sorta"),
    ("it", "La pazienza è amara ma il suo frutto è dolcissimo alla fine"),
    ("it", "Chi non risica non rosica e rimane dov'è per sempre"),
    ("it", "Il tempo è galantuomo e prima o poi rivela tutto ciò che è"),
    ("it", "Nessun uomo è un'isola intera di per se stesso nel mare"),
    ("it", "La strada per l'inferno è lastricata di buone intenzioni"),
    ("it", "Chi cerca trova e chi non cerca non trova mai nulla"),
    ("it", "La speranza è il pane quotidiano di chi vive con dignità"),
    ("it", "Il silenzio è d'oro quando le parole farebbero solo danno"),
    ("it", "Ogni giorno è una nuova pagina del libro della tua vita"),
    ("it", "La memoria è il diario che ognuno porta sempre con sé"),
    ("it", "Non tutto ciò che luccica è oro né ogni parola è sincera"),
    ("it", "La semplicità è la forma più alta di ogni vera sofisticazione"),
    ("it", "Chi semina bontà raccoglie amicizia sincera e pace interiore"),
    ("it", "Il rispetto non si compra ma si guadagna con i fatti concreti"),
    ("it", "La cultura è ciò che resta quando si è dimenticato tutto"),
    ("it", "Chi ha fretta è già in ritardo, dice il saggio del villaggio"),
    ("it", "L'esperienza è maestra di vita ma è cara da pagare sempre"),
    ("it", "Non c'è peggior sordo di chi non vuol sentire la verità"),
    ("it", "La fantasia è la porta attraverso cui entra la creatività"),
    ("it", "Chi vive di speranza muore di delusione se non agisce mai"),
    ("it", "Il cuore ha le sue ragioni che la ragione non conosce"),
    ("it", "La fiducia si costruisce in anni e si distrugge in secondi"),
    ("it", "Chi parla troppo spesso non ha nulla di importante da dire"),
    ("it", "La gratitudine è il più bel fiore che cresce nell'anima"),
    ("it", "Non vale la pena di vivere senza amare e senza essere amati"),
    ("it", "Il coraggio di fallire è la radice di ogni grande successo"),
    ("it", "La bellezza dell'anima supera di gran lunga quella del corpo"),
    ("it", "Chi non apprezza il poco non merita il molto che vorrebbe"),
    ("it", "L'amore vero non invecchia mai perché si rinnova ogni giorno"),
    ("it", "La disciplina è il ponte tra i sogni e la loro realizzazione"),
    ("it", "Non esistono problemi senza soluzione, solo soluzioni non trovate"),
    ("it", "Il tempo libero è il tempo in cui si diventa ciò che si è"),
    ("it", "Chi ama se stesso può amare gli altri con pienezza e gioia"),
    ("it", "La conoscenza è potere ma la saggezza è la sua applicazione"),
    ("it", "Non si può fermare il vento ma si può orientare la vela"),
    ("it", "Il libro è lo specchio in cui l'anima si guarda e si conosce"),
    ("it", "La gioia di vivere si trova nelle piccole cose di ogni giorno"),
    ("it", "Chi è padrone di sé stesso è più ricco di chi possiede tutto"),
    ("it", "La vera amicizia si vede nel momento del bisogno più grande"),
    ("it", "Non esiste autunno senza la promessa di una nuova primavera"),
    ("it", "Il sorriso è il linguaggio universale che tutti comprendono"),
    ("it", "La forza non viene dal corpo ma dalla volontà dello spirito"),
    ("it", "Chi dimentica il passato è condannato a riviverlo ancora"),
    ("it", "La verità è come il sole: si può offuscare ma non spegnere"),
    ("it", "Non c'è vento favorevole per chi non sa dove vuole andare"),
    ("it", "Il carattere si rivela nella difficoltà e non nella comodità"),
    ("it", "La vita è un'eco: restituisce sempre ciò che hai inviato"),
    ("it", "Chi non cade non impara a camminare con sicurezza e grazia"),
    ("it", "L'uomo saggio parla poco e ascolta molto con attenzione"),
    ("it", "Non fare agli altri ciò che non vorresti fosse fatto a te"),
    ("it", "Il talento è il dono di Dio, ma la perseveranza è la nostra"),
    ("it", "La vita senza scopo è come una barca senza timone in mare"),
    ("it", "Chi ha imparato ad aspettare ha imparato tutto ciò che serve"),
    ("it", "La pace interiore è il tesoro più prezioso che esista al mondo"),
    ("it", "Non cercare la perfezione; cerca il miglioramento continuo"),
    ("it", "Il viaggio più importante è quello che si compie dentro di sé"),
    ("it", "La curiosità è il motore della scoperta e dell'innovazione"),
    ("it", "Chi dà senza aspettarsi nulla in cambio riceve il centuplo"),
    ("it", "L'umiltà è la madre di tutte le virtù e la figlia della fede"),
    ("it", "Non basta avere il dono; bisogna anche coltivarlo con cura"),
    ("it", "La mente è come uno specchio che riflette ciò che le stai davanti"),
    ("it", "Chi lavora con amore tesse se stesso nel lavoro fatto bene"),
    ("it", "La saggezza non è nel sapere tutto ma nel saper usare il poco"),
    ("it", "Non si ama ciò che si conosce pienamente, si ama il mistero"),

    # ═══════════════════════════════════════════════════════
    # PORTUGUÊS (pt)
    # ═══════════════════════════════════════════════════════
    ("pt", "Quem não arrisca não petisca e fica sempre no mesmo lugar"),
    ("pt", "A vida é bela para quem sabe apreciá-la com gratidão"),
    ("pt", "Mais vale um pássaro na mão do que dois a voar no céu"),
    ("pt", "Quem cedo madruga mais longe chega na sua caminhada"),
    ("pt", "A pressa é inimiga da perfeição e amiga do arrependimento"),
    ("pt", "Não deixes para amanhã o que podes fazer hoje com alegria"),
    ("pt", "A amizade é o único tesouro que aumenta quando se partilha"),
    ("pt", "Quem muito fala pouco sabe e muito erra no que diz"),
    ("pt", "O silêncio é a resposta mais sábia para certas perguntas"),
    ("pt", "A persistência é a mãe do sucesso e a filha da fé"),
    ("pt", "Não há mal que sempre dure nem bem que nunca termine"),
    ("pt", "A gratidão é a memória do coração que não esquece o bem"),
    ("pt", "Quem planta bondade colhe amizade e paz no coração"),
    ("pt", "O conhecimento é a única coisa que cresce quando se partilha"),
    ("pt", "Não se pode comprar felicidade mas pode-se construí-la"),
    ("pt", "A força mais poderosa do mundo é a de um coração que ama"),
    ("pt", "Quem tem saúde tem tudo o que precisa para ser feliz"),
    ("pt", "O tempo é o único bem que não se pode comprar nem recuperar"),
    ("pt", "Não existe vitória sem luta nem glória sem sacrifício"),
    ("pt", "A beleza do coração é a única que nunca envelhece de verdade"),
    ("pt", "Quem semeia com lágrimas colhe com alegria e abundância"),
    ("pt", "O livro é o melhor companheiro de viagem que existe"),
    ("pt", "Não há maior pobreza do que a pobreza de espírito e alma"),
    ("pt", "A disciplina é a ponte entre os sonhos e a sua realização"),
    ("pt", "Quem não perdoa não pode ser perdoado nem receber graça"),
    ("pt", "O caminho faz-se caminhando com fé e determinação plena"),
    ("pt", "Não se pode atravessar o mar sem perder de vista a margem"),
    ("pt", "A simplicidade é a elegância suprema dos espíritos livres"),
    ("pt", "Quem tem um bom amigo tem um tesouro que não tem preço"),
    ("pt", "O futuro é criado por aqueles que acreditam e trabalham"),
    ("pt", "Não há obstáculo tão grande que a vontade não supere"),
    ("pt", "A sabedoria é a arte de viver bem com o que se tem"),
    ("pt", "Quem aprende com os erros dos outros é muito mais sábio"),
    ("pt", "O amor que não cresce está destinado a diminuir e morrer"),
    ("pt", "Não há caminho certo para fazer a coisa errada na vida"),
    ("pt", "A confiança é a base de toda a relação humana duradoura"),
    ("pt", "Quem ajuda o próximo ajuda a si mesmo sem o saber"),
    ("pt", "O coração que ama não envelhece com o passar dos anos"),
    ("pt", "Não se mede o amor pela duração mas pela profundidade"),
    ("pt", "A humildade é o sinal mais certo da verdadeira grandeza"),
    ("pt", "Quem não semeia não pode esperar colher o que não plantou"),
    ("pt", "O sábio fala porque tem algo a dizer e não para ser ouvido"),
    ("pt", "Não há felicidade possível sem um pouco de sofrimento"),
    ("pt", "A vida ensina o que nenhuma escola foi capaz de nos dar"),
    ("pt", "Quem tem fé move montanhas e atravessa mares tempestuosos"),
    ("pt", "O presente é o único tempo em que podemos agir e mudar"),
    ("pt", "Não basta ter talento é preciso também ter determinação"),
    ("pt", "A bondade é a linguagem que os surdos podem ouvir e ver"),
    ("pt", "Quem guarda sempre encontra no momento certo da vida"),
    ("pt", "O trabalho honesto é a fundação de toda a dignidade humana"),
    ("pt", "Não há noite tão longa que não termine com uma aurora"),
    ("pt", "A paz que excede todo o entendimento guarda o nosso coração"),
    ("pt", "Quem tem virtude tem tudo o que precisa para ser grande"),
    ("pt", "O segredo da alegria está em dar mais do que se recebe"),
    ("pt", "Não há inimigo mais perigoso do que a própria ignorância"),
    ("pt", "A criança que não brincan não pode tornar-se num adulto pleno"),
    ("pt", "Quem luta com persistência acaba por vencer qualquer obstáculo"),
    ("pt", "O silêncio às vezes é a forma mais eloquente de responder"),
    ("pt", "Não existe distância que o amor verdadeiro não consiga vencer"),
    ("pt", "A boa fama é mais preciosa do que todo o ouro do mundo"),

    # ═══════════════════════════════════════════════════════
    # ESPAÑOL (es)
    # ═══════════════════════════════════════════════════════
    ("es", "Más vale pájaro en mano que ciento volando por el aire"),
    ("es", "Quien madruga Dios le ayuda con su gracia y su favor"),
    ("es", "A palabras necias oídos sordos y a males males remedios"),
    ("es", "El que persevera alcanza lo que se propone en esta vida"),
    ("es", "Quien a buen árbol se arrima buena sombra le cobija"),
    ("es", "No hay mal que por bien no venga con el tiempo y paciencia"),
    ("es", "A cada cerdo le llega su San Martín, dice el refrán"),
    ("es", "Dime de qué presumes y te diré de qué careces en verdad"),
    ("es", "El que mucho abarca poco aprieta y todo lo pierde al fin"),
    ("es", "Camarón que se duerme la corriente se lo lleva sin remedio"),
    ("es", "No por mucho madrugar amanece más temprano el sol claro"),
    ("es", "Quien bien te quiere te hará llorar pero también reír"),
    ("es", "La avaricia rompe el saco y la codicia pierde lo ganado"),
    ("es", "De tal palo tal astilla cuando la manzana no rueda lejos"),
    ("es", "Más vale malo conocido que bueno por conocer en la vida"),
    ("es", "El diablo sabe más por viejo que por diablo propiamente"),
    ("es", "No hay peor cuña que la de la misma madera bien ajustada"),
    ("es", "Amor con amor se paga y con desamor se acaba para siempre"),
    ("es", "A lo hecho pecho y hay que afrontar las consecuencias"),
    ("es", "Agua que no has de beber déjala correr hacia el mar"),
    ("es", "El que no llora no mama y el que no se mueve no avanza"),
    ("es", "Bueno es el cilantro pero no tanto que amargue el guiso"),
    ("es", "No es lo mismo llamar al diablo que verlo llegar de frente"),
    ("es", "Genio y figura hasta la sepultura, dice el viejo refrán"),
    ("es", "El hombre es fuego y la mujer estopa y viene el diablo"),
    ("es", "Aunque la mona se vista de seda mona se queda al final"),
    ("es", "El que escupe al cielo en la cara le cae a sí mismo"),
    ("es", "A enemigo que huye puente de plata para que no vuelva"),
    ("es", "Barriga llena corazón contento y mente más despejada"),
    ("es", "Al mal tiempo buena cara y a buen tiempo mejor actitud"),
    ("es", "El que siembra tempestades recoge tormentas sin remedio"),
    ("es", "A buen hambre no hay pan duro ni comida que no sepa bien"),
    ("es", "No hay mejor médico que el que ha padecido la enfermedad"),
    ("es", "El consejo de la vejez es una luz que alumbra sin quemar"),
    ("es", "Con la misma vara que midas serás medido en tu momento"),
    ("es", "El miedo guarda la viña pero la valentía cosecha el fruto"),
    ("es", "Quien tiene vergüenza ni come ni almuerza ni cena nunca"),
    ("es", "La experiencia es la madre de la ciencia y la abuela del saber"),
    ("es", "No hay atajo sin trabajo ni victoria sin su propio precio"),
    ("es", "El amor propio es el amor que nunca decepciona a nadie"),
    ("es", "Más hace el que quiere que el que puede si no quiere nada"),
    ("es", "A río revuelto ganancia de pescadores avisados y audaces"),
    ("es", "El que parte y reparte se lleva la mejor parte siempre"),
    ("es", "No hay mal que cien años dure aunque el cuerpo sí que siente"),
    ("es", "Quien no tiene cabeza tiene que tener piernas para correr"),
    ("es", "La buena vida comienza cuando dejas de compararte con otros"),
    ("es", "El amor no pide permiso para entrar ni para quedarse dentro"),
    ("es", "Quien da pan a perros ajenos pierde el pan y el perro"),
    ("es", "No dejes para mañana la alegría que puedes sentir hoy mismo"),
    ("es", "La tierra prometida solo se alcanza con fe y perseverancia"),
    ("es", "Quien espera desespera si no tiene paciencia en el camino"),
    ("es", "No hay viento favorable para quien no sabe adónde ir"),
    ("es", "El talento sin esfuerzo es como una semilla sin agua ni sol"),
    ("es", "Quien vive bien no tiene miedo de morir cuando llegue el día"),
    ("es", "La paz interior vale más que todas las riquezas del mundo"),
    ("es", "No hay mayor sabiduría que la de conocer los propios límites"),
    ("es", "El que busca la paz la encuentra y quien busca guerra la halla"),
    ("es", "Quien da de corazón nunca da demasiado ni se arrepiente"),
    ("es", "La honradez es la piedra angular de toda vida bien vivida"),
    ("es", "No hay libro tan malo que no tenga algo bueno en sus páginas"),
    ("es", "El que no tiene enemigos es que no ha hecho nada memorable"),
    ("es", "Quien aprende sin pensar pierde el tiempo y quien piensa sin"),
    ("es", "La vida es como un espejo que nos devuelve lo que damos"),
    ("es", "No hay nadie más peligroso que el que tiene media verdad"),
    ("es", "El que no sabe agradecer lo que tiene no merece más todavía"),
    ("es", "Quien vive sin ilusiones vive a medias y muere entero al fin"),
    ("es", "La memoria es el único paraíso del que nadie puede echarnos"),
    ("es", "No hay mejor herencia que una buena educación y buenos valores"),
    ("es", "El que no cree en nada no tiene nada por lo que luchar"),
    ("es", "Quien ayuda sin esperar recompensa es verdaderamente generoso"),
    ("es", "La valentía no es no tener miedo sino actuar a pesar de él"),
    ("es", "No hay cosa más cara que la que se consigue fácilmente"),
    ("es", "El corazón tiene razones que la razón no alcanza ni entiende"),

    # ═══════════════════════════════════════════════════════
    # ENGLISH (en)
    # ═══════════════════════════════════════════════════════
    ("en", "The early bird catches the worm but the second mouse gets"),
    ("en", "Actions speak louder than words in every situation of life"),
    ("en", "Every cloud has a silver lining if you look carefully enough"),
    ("en", "Where there is a will there is always a way to achieve it"),
    ("en", "The pen is mightier than the sword in the long run of time"),
    ("en", "Two wrongs do not make a right no matter what others say"),
    ("en", "The grass is always greener on the other side of the fence"),
    ("en", "Don't count your chickens before they are hatched and ready"),
    ("en", "You cannot judge a book by its cover no matter how pretty"),
    ("en", "Better safe than sorry when it comes to making life choices"),
    ("en", "Time heals all wounds if you give it enough space and patience"),
    ("en", "Every dog has its day and every person their moment of glory"),
    ("en", "A stitch in time saves nine and a word of kindness saves more"),
    ("en", "All good things must come to an end sooner or later in life"),
    ("en", "If it ain't broke don't fix it and leave well enough alone"),
    ("en", "No pain no gain is the motto of champions and great achievers"),
    ("en", "Practice makes perfect if you practice the right things well"),
    ("en", "You reap what you sow in life and in relationships always"),
    ("en", "Absence makes the heart grow fonder when love is truly real"),
    ("en", "The truth will set you free but first it will make you uncomfortable"),
    ("en", "Necessity is the mother of invention and the father of progress"),
    ("en", "A penny saved is a penny earned said the frugal philosopher"),
    ("en", "Birds of a feather flock together and share common destinies"),
    ("en", "Don't bite the hand that feeds you even when you are hungry"),
    ("en", "Fortune favors the bold who dare to take the first brave step"),
    ("en", "Honesty is the best policy in all things great and small alike"),
    ("en", "Knowledge is power but wisdom is knowing how to use it well"),
    ("en", "Laughter is the best medicine for the soul in difficult times"),
    ("en", "Look before you leap and think before you speak or act rashly"),
    ("en", "Make hay while the sun shines and seize the day while you can"),
    ("en", "Never put off till tomorrow what you can do today with ease"),
    ("en", "No man is an island entire of itself in this interconnected world"),
    ("en", "Once bitten twice shy is what experience teaches those who learn"),
    ("en", "Out of sight out of mind unless the heart truly remembers"),
    ("en", "Rome was not built in a day and neither is a great character"),
    ("en", "The best things in life are free and cannot be bought at all"),
    ("en", "The more things change the more they stay the same in essence"),
    ("en", "There is no time like the present to begin what you must do"),
    ("en", "Time waits for no man and the clock does not stop for anyone"),
    ("en", "United we stand divided we fall is the wisdom of the ages"),
    ("en", "Virtue is its own reward and needs no other justification"),
    ("en", "Waste not want not is the rule of the wise and the prudent"),
    ("en", "When the going gets tough the tough get going and persist"),
    ("en", "Wisdom comes with age but age does not always bring wisdom"),
    ("en", "You can lead a horse to water but you cannot make it drink"),
    ("en", "A friend in need is a friend indeed and worth more than gold"),
    ("en", "All roads lead to Rome but not all roads are worth traveling"),
    ("en", "An apple a day keeps the doctor away they say in the country"),
    ("en", "Ask and you shall receive seek and you shall find in life"),
    ("en", "Be careful what you wish for because you just might get it"),
    ("en", "Better to have loved and lost than never to have loved at all"),
    ("en", "By the time a man realizes his father was right, he has a son"),
    ("en", "Do unto others as you would have them do unto you always"),
    ("en", "Every action has an equal and opposite reaction in all things"),
    ("en", "Faith can move mountains when it is genuine and sincere"),
    ("en", "Give credit where credit is due and gratitude where it belongs"),
    ("en", "He who laughs last laughs best and longest in the end"),
    ("en", "If you want peace prepare for it but also work toward it"),
    ("en", "It takes a village to raise a child properly and well"),
    ("en", "Judge not lest ye be judged by the same standard you apply"),
    ("en", "Keep your friends close and your enemies closer if possible"),
    ("en", "Let sleeping dogs lie and let the past be where it belongs"),
    ("en", "Love is blind but marriage is a real eye opener for all"),
    ("en", "Many hands make light work when people cooperate together"),
    ("en", "Never look a gift horse in the mouth or question generosity"),
    ("en", "Old habits die hard no matter how much one wants to change"),
    ("en", "One man's trash is another man's treasure in this world"),
    ("en", "People who live in glass houses should not throw stones ever"),
    ("en", "Still waters run deep and quiet people think the most deeply"),
    ("en", "The apple does not fall far from the tree in most cases"),
    ("en", "There are two sides to every story and the truth lies between"),
    ("en", "To err is human to forgive is divine according to Alexander"),
    ("en", "Truth is the first casualty of war and the last to return"),
    ("en", "Walk the talk and let your actions match your spoken words"),
    ("en", "What goes around comes around sooner or later in this life"),
    ("en", "Where there is smoke there is fire and where love warmth"),
    ("en", "Yesterday is gone tomorrow is uncertain but today is yours"),
    ("en", "You are what you eat but even more what you think and believe"),
    ("en", "A calm sea never made a skilled sailor worth their salt"),
    ("en", "Above all to thine own self be true and it follows night"),
    ("en", "All you need is love and the rest will follow in due time"),
    ("en", "An ounce of prevention is worth a pound of cure every time"),
    ("en", "Art is not what you see but what you make others see with you"),
    ("en", "Be the change you want to see in this world every single day"),
    ("en", "Children are the living messages we send to a future we won't"),
    ("en", "Creativity is intelligence having fun with the world around"),
    ("en", "Darkness cannot drive out darkness only light can do that"),
    ("en", "Each moment of happiness makes up for a lifetime of trouble"),
    ("en", "Even the darkest night will end and the sun will rise again"),
    ("en", "Every moment is a fresh beginning if you choose to see it so"),
    ("en", "Fall seven times stand up eight and you will eventually win"),
    ("en", "Genius is one percent inspiration ninety-nine percent sweat"),
    ("en", "Give a man a fish and he eats a day teach him and forever"),
    ("en", "Go where you are celebrated not where you are merely tolerated"),
    ("en", "Great minds discuss ideas average minds events small minds people"),
    ("en", "He is richest who is content with the least for want is wealth"),
    ("en", "History will be kind to me for I intend to write it myself"),
    ("en", "Home is not a place it is a feeling of safety and belonging"),
    ("en", "I am not afraid of storms for I am learning to sail my ship"),
    ("en", "I attribute my success to this: I never gave or took an excuse"),
    ("en", "If opportunity does not knock build a door and go through"),
    ("en", "In the end it is not the years in your life that count most"),
    ("en", "It always seems impossible until someone brave enough does it"),
    ("en", "Life is short and the world is wide so go out and explore it"),
    ("en", "Look at the stars look how they shine for you and everything"),
    ("en", "Love is not love which alters when it alteration finds within"),
    ("en", "Never give in never give up never surrender to despair alone"),
    ("en", "No act of kindness no matter how small is ever really wasted"),
    ("en", "Nothing is impossible the word itself says I am possible now"),
    ("en", "Once you choose hope anything is possible for the willing soul"),
    ("en", "Opportunity is missed by most because it looks like hard work"),
    ("en", "Our lives begin to end the day we become silent about things"),
    ("en", "Start where you are use what you have do what you can today"),
    ("en", "The best preparation for tomorrow is doing your best today"),
    ("en", "The hardest battle you will ever face is the one within self"),
    ("en", "The man who moves mountains begins by carrying small stones"),
    ("en", "The past is a place of reference not a place of residence ever"),
    ("en", "The road to success is always under construction and repair"),
    ("en", "The strongest people are not those who show strength but feel"),
    ("en", "There is no elevator to success you have to take the stairs"),
    ("en", "To accomplish great things we must dream as well as act boldly"),
    ("en", "Turn your wounds into wisdom and your failures into lessons"),
    ("en", "We do not remember days we remember moments that touched us"),
    ("en", "What you do speaks so loudly I cannot hear what you say now"),
    ("en", "When one door closes another opens but we look at closed doors"),
    ("en", "With the realization of one's own potential comes confidence"),
    ("en", "You become what you believe not what you think you want to be"),
    ("en", "Your time is limited so do not waste it living someone else"),
    ("en", "Accept what is let go what was have faith in what will be"),
    ("en", "Attitude is a little thing that makes a very big difference"),
    ("en", "Be a voice not an echo in the crowd of ordinary thinking"),
    ("en", "Believe you can and you are halfway there already in your mind"),
    ("en", "Chase the vision not the money and the money will follow you"),
    ("en", "Comparison is the thief of joy so focus on your own journey"),
    ("en", "Don't be pushed around by the fears in your mind, lead heart"),
    ("en", "Each day provides its own gifts if you choose to receive them"),
    ("en", "Embrace uncertainty some of the most beautiful chapters will"),
    ("en", "Everything you've ever wanted is on the other side of your fear"),
    ("en", "For every minute you are angry you lose sixty seconds of joy"),
    ("en", "Get up every morning with the thought that something wonderful"),
    ("en", "Hard work beats talent when talent does not work hard enough"),
    ("en", "Have enough courage to start and enough heart to finish it"),
    ("en", "I will not let anyone walk through my mind with dirty feet"),
    ("en", "If you cannot do great things do small things in a great way"),
    ("en", "In a gentle way you can shake the world if you try with heart"),
    ("en", "It does not matter how slowly you go as long as you do not"),
    ("en", "Just because my path is different does not mean I am lost now"),
    ("en", "Keep your eyes on the stars and your feet on the ground firm"),
    ("en", "Let your smile change the world but do not let the world change"),
    ("en", "Life is not about waiting for the storm to pass but dancing"),
    ("en", "Make each day your masterpiece and give it everything you have"),
    ("en", "No matter how hard the past you can always begin again today"),
    ("en", "Nothing is predestined the obstacles of your past can become"),
    ("en", "One small positive thought in the morning can change your day"),
    ("en", "Our greatest glory is not in never failing but in rising every"),
    ("en", "Pursue what catches your heart not what catches your eye only"),
    ("en", "Set your goals high and do not stop until you get there fully"),
    ("en", "Small steps in the right direction can turn out to be the biggest"),
    ("en", "The difference between ordinary and extraordinary is that little"),
    ("en", "The greatest risk is to take no risk at all when you have the chance"),
    ("en", "The journey of a thousand miles begins beneath your own feet"),

    # ═══════════════════════════════════════════════════════
    # ROMÂNĂ (ro) — adicionales
    # ═══════════════════════════════════════════════════════
    ("ro", "Prietenia adevărată nu se cumpără cu bani ci se câștigă"),
    ("ro", "Cine ajută pe altul se ajută pe sine fără să știe"),
    ("ro", "Răul nu vine niciodată singur și nici binele nu vine singur"),
    ("ro", "Cel mai prețios lucru din viață este sănătatea sufletului"),
    ("ro", "Nu amâna pentru mâine ceea ce poți face azi cu bucurie"),
    ("ro", "Fericirea nu se găsește se construiește zi cu zi cu iubire"),
    ("ro", "Vorbele bune nu costă nimic dar valorează enorm de mult"),
    ("ro", "Cine nu riscă niciodată nu câștigă nimic în viața asta"),
    ("ro", "Adevărul spus cu bunătate ajunge la suflet mai repede"),
    ("ro", "Cunoașterea este singura bogăție pe care nimeni nu ți-o ia"),
    ("ro", "Nu este niciodată prea târziu să devii ceea ce ai putea fi"),
    ("ro", "Dragostea adevărată crește pe măsură ce trece timpul"),
    ("ro", "Cel mai bun moment pentru a planta un copac a fost acum"),
    ("ro", "Omul harnic și perseverent ajunge departe în viața aceasta"),
    ("ro", "Nu există noapte atât de lungă ca să nu se termine cu zori"),
    ("ro", "Credința mută munții când este sinceră și venită din inimă"),
    ("ro", "Cel mai mare câștig este pacea interioară și liniștea sufletului"),
    ("ro", "Nu judeca pe alții după aparențe ci după faptele lor concrete"),
    ("ro", "Înțelepciunea nu este în a ști totul ci în a folosi bine puținul"),
    ("ro", "Răbdarea este virtutea celui care știe că timpul lucrează pentru el"),

    # ═══════════════════════════════════════════════════════
    # CATALÀ (ca) — adicionales
    # ═══════════════════════════════════════════════════════
    ("ca", "Qui no s'aventura no travessa la mar ni guanya res"),
    ("ca", "La veritat és com l'oli sempre sura per sobre de l'aigua"),
    ("ca", "Qui bé et vol et farà plorar però també et farà riure"),
    ("ca", "No totes les coses que lluen són or ni tot somriure és sincer"),
    ("ca", "L'experiència és la mare de la ciència i l'àvia del saber"),
    ("ca", "Qui sembla bondat recull amistat i pau en el seu camí"),
    ("ca", "La perseverança és la clau que obre totes les portes tancades"),
    ("ca", "No hi ha millor mestre que el fracàs ben après i superat"),
    ("ca", "Qui no s'atura a reflexionar camina de pressa cap al buit"),
    ("ca", "La senzillesa és l'elegància suprema dels esperits lliures"),
    ("ca", "No cal fer gran soroll per fer gran cosa amb paciència"),
    ("ca", "L'home que sap escoltar aprèn més que l'home que parla molt"),
    ("ca", "Qui dóna sense esperar res a canvi és vertaderament lliure"),
    ("ca", "La cultura és la llum que il·lumina el camí de la humanitat"),
    ("ca", "No hi ha riquesa més gran que tenir un cor net i tranquil"),
    ("ca", "Qui treballa amb amor posa una mica d'ell en l'obra feta"),
    ("ca", "La pau interior és el tresor més valuós que hom pot tenir"),
    ("ca", "No es pot encendre una llum sense fer una mica de foscor"),
    ("ca", "Qui aprèn dels errors dels altres és molt més savi que nosaltres"),
    ("ca", "L'amistat és la flor més bella del jardí de la vida"),

    # ═══════════════════════════════════════════════════════
    # GALEGO (gl) — adicionales
    # ═══════════════════════════════════════════════════════
    ("gl", "Quen non traballa non come e quen non come non pode traballar"),
    ("gl", "A vida é un camiño que se fai andando con fe e esperanza"),
    ("gl", "Non hai noite tan longa que non remate cunha nova alba"),
    ("gl", "Quen dá sen esperar recompensa é verdadeiramente libre"),
    ("gl", "A perseveranza é a chave que abre todas as portas pechadas"),
    ("gl", "Non hai maior riqueza ca a dun corazón limpo e tranquilo"),
    ("gl", "Quen aprende dos erros alleos é moito máis sabio ca nos"),
    ("gl", "A amizade é a flor máis fermosa do xardín da nosa vida"),
    ("gl", "Non se pode facer tortilla sen romper os ovos primeiro"),
    ("gl", "Quen ten saúde ten todo o que precisa para ser feliz"),

    # ═══════════════════════════════════════════════════════
    # LATINA (la) — adicionales
    # ═══════════════════════════════════════════════════════
    ("la", "Dum vivimus vivamus et gaudeamus igitur in hac vita"),
    ("la", "Pax vobiscum et cum spiritu tuo in aeternum amen"),
    ("la", "Verba volant scripta manent in memoria et in corde"),
    ("la", "Qui tacet consentire videtur cum clamare debuisset"),
    ("la", "Dura lex sed lex et iustitia fundamentum regnorum est"),
    ("la", "Fac et spera quia fortuna iuvat qui laborat diligenter"),
    ("la", "Mors certa hora incerta sed vita brevis et ars longa"),
    ("la", "In hoc signo vinces et veritas te liberabit semper"),
    ("la", "Ora et labora et bene cura corpus sanum in mente sana"),
    ("la", "Qui scribit bis legit et bis intellegit quod scribitur"),
    ("la", "Amor patriae nostra lex suprema et fons virtutis"),
    ("la", "Beati pauperes spiritu quoniam ipsorum est regnum caeli"),
    ("la", "Nihil novi sub sole et omnia quae fuerunt iterum erunt"),
    ("la", "Sic itur ad astra per aspera et per multos labores"),
    ("la", "Ad maiorem Dei gloriam et hominum salutem semper"),
    ("la", "Ubi concordia ibi victoria et ubi discordia ibi ruina"),
    ("la", "Finis coronat opus et perseverantia omnia vincit forte"),

    # ═══════════════════════════════════════════════════════
    # OCCITAN (oc) — adicionales
    # ═══════════════════════════════════════════════════════
    ("oc", "La vida es un viatge que se fa caminant amb coratge"),
    ("oc", "Qui dòna sens esperar res en retorn es vertadièrament liure"),
    ("oc", "La perseverança es la clau que durbís totas las pòrtas"),
    ("oc", "Non i a nuèch tant longa que s'acabe pas amb l'alba"),
    ("oc", "Qui semena bontat recampa amistat e patz dins son còr"),
    ("oc", "La simplesà es l'elegància suprema dels esperits liures"),
    ("oc", "Qui apren dels errors dels autres es mai savi que nosaltres"),
    ("oc", "Lo trabalh donat amb amor fa de l'òme un mèstre"),
    ("oc", "La patz interiora es lo tesor mai precions de la vida"),
    ("oc", "Qui parla tròp sovent res important a dire lo monde"),
]

path = r'C:\Users\nicoa\romance_dataset.csv'
with open(path, encoding='utf-8') as f:
    existing = list(csv.DictReader(f))

existing_texts = {r['text'] for r in existing}
max_id = max(int(r['id']) for r in existing)
needed = 1500 - len(existing)
print(f"Entradas actuales: {len(existing)}, faltan: {needed}")

seen = set(existing_texts)
filtered = []
for lang, text in new_phrases:
    t = text.strip()
    if 50 <= len(t) <= 100 and t not in seen:
        seen.add(t)
        filtered.append((lang, t))

print(f"Frases nuevas válidas (50-100 chars, sin duplicados): {len(filtered)}")
final_new = filtered[:needed]
print(f"Agregando: {len(final_new)}")

all_rows = existing.copy()
for i, (lang, text) in enumerate(final_new, max_id + 1):
    all_rows.append({
        'id': i,
        'language': lang,
        'text': text,
        'text_normalized': normalize(text),
        'char_count': len(text),
    })

with open(path, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(
        f,
        fieldnames=['id', 'language', 'text', 'text_normalized', 'char_count'],
        quoting=csv.QUOTE_ALL
    )
    writer.writeheader()
    writer.writerows(all_rows)

with open(path, encoding='utf-8') as f:
    final = list(csv.DictReader(f))

lang_counts = Counter(r['language'] for r in final)
lengths = [int(r['char_count']) for r in final]
print(f"\nTotal entradas: {len(final)}")
print(f"Chars: min={min(lengths)}, max={max(lengths)}, avg={sum(lengths)/len(lengths):.1f}")
print("\nDistribucion por idioma:")
for lang, count in sorted(lang_counts.items()):
    print(f"  {lang}: {count}")
