import csv, unicodedata
from collections import Counter

def normalize(text):
    ligatures = {
        'œ': 'oe', 'Œ': 'OE', 'æ': 'ae', 'Æ': 'AE',
        'ß': 'ss', 'ð': 'd', 'Ð': 'D', 'þ': 'th', 'Þ': 'TH',
        'ŋ': 'n', 'ı': 'i',
    }
    for src, dst in ligatures.items():
        text = text.replace(src, dst)
    nfkd = unicodedata.normalize('NFKD', text)
    return ''.join(c for c in nfkd if unicodedata.category(c) != 'Mn')

new_phrases = [
    # ═══════════════════════════════════════════════════════
    # FRANÇAIS (fr)
    # ═══════════════════════════════════════════════════════
    ("fr", "Il n'y a pas de vents favorables pour qui ne sait où aller"),
    ("fr", "La vie est courte, l'art est long et le temps fuit sans cesse"),
    ("fr", "Un homme averti en vaut deux dans toutes les circonstances"),
    ("fr", "Mieux vaut être seul que mal accompagné, dit la sagesse"),
    ("fr", "Les chiens aboient et la caravane passe sans s'arrêter"),
    ("fr", "Nul n'est prophète en son pays ni maître chez lui parfois"),
    ("fr", "La charité bien ordonnée commence toujours par soi-même"),
    ("fr", "Quand on n'a pas ce que l'on aime on aime ce que l'on a"),
    ("fr", "Vouloir c'est pouvoir quand la volonté est ferme et sincère"),
    ("fr", "La pauvreté n'est pas un vice mais c'est une grande gêne"),
    ("fr", "Il n'est point de sot métier il n'est que de sottes gens"),
    ("fr", "On revient toujours à ses premières amours tôt ou tard"),
    ("fr", "Le sage doute de tout sauf de sa propre capacité à douter"),
    ("fr", "L'union fait la force et la division prépare la défaite"),
    ("fr", "Bien faire et laisser dire est la règle du sage homme"),
    ("fr", "Il vaut mieux être riche et bien portant que pauvre et malade"),
    ("fr", "La nuit porte conseil car elle calme les passions brûlantes"),
    ("fr", "Ce qui ne te tue pas te rend plus fort et plus résistant"),
    ("fr", "L'enfer est pavé de bonnes intentions jamais réalisées"),
    ("fr", "Les paroles s'envolent mais les écrits restent pour toujours"),
    ("fr", "Qui s'excuse s'accuse et révèle ce qu'il voulait cacher"),
    ("fr", "L'avare est toujours pauvre car il pense toujours manquer"),
    ("fr", "Noblesse oblige et celui qui l'a doit la montrer chaque jour"),
    ("fr", "Petite pluie abat grand vent et petite bonté fait grand bien"),
    ("fr", "Il ne faut pas déshabiller Pierre pour habiller Paul jamais"),
    ("fr", "Tel père tel fils dit-on souvent mais ce n'est pas toujours vrai"),
    ("fr", "La discrétion est la politesse de l'âme bien élevée"),
    ("fr", "On ne prête qu'aux riches et c'est là une grande injustice"),
    ("fr", "Aide-toi le ciel t'aidera car Dieu aide ceux qui agissent"),
    ("fr", "Qui vivra verra et qui attendra obtiendra ce qu'il attend"),
    ("fr", "Les bons comptes font les bons amis durables et sincères"),
    ("fr", "Il faut battre le fer quand il est chaud sans attendre"),
    ("fr", "La vengeance est un plat qui se mange froid dit-on souvent"),
    ("fr", "Qui se couche avec des chiens se lève avec des puces"),
    ("fr", "L'appétit vient en mangeant et l'amour en aimant vraiment"),
    ("fr", "Tout vient à point à qui sait attendre avec patience"),
    ("fr", "Le diable est dans les détails et Dieu dans la vue d'ensemble"),
    ("fr", "Mieux vaut prévenir que guérir quand il est encore possible"),
    ("fr", "Un mal pour un bien arrive parfois dans les vies humaines"),
    ("fr", "La fin justifie les moyens selon certains penseurs politiques"),
    ("fr", "Rien ne sert de courir il faut partir à point dit La Fontaine"),
    ("fr", "Qui a bu boira et qui a menti mentira encore demain"),
    ("fr", "La raison et le cœur se disputent souvent sans vainqueur"),
    ("fr", "Qui n'entend qu'une cloche n'entend qu'un son incomplet"),
    ("fr", "L'homme propose et Dieu dispose de nos projets à sa guise"),
    ("fr", "La beauté du monde est dans sa diversité et ses contrastes"),
    ("fr", "Il ne faut pas mettre tous ses œufs dans le même panier"),
    ("fr", "Les absents ont toujours tort dans les histoires des présents"),
    ("fr", "Un bienfait n'est jamais perdu même s'il semble oublié"),
    ("fr", "La sagesse des nations vaut souvent mieux que la science"),
    ("fr", "On ne change pas une équipe qui gagne selon les pragmatiques"),
    ("fr", "Le malheur des uns fait parfois le bonheur des autres hélas"),
    ("fr", "Chassez le naturel il revient toujours au galop sans fail"),
    ("fr", "Il faut tourner sept fois sa langue avant de parler"),
    ("fr", "La simplicité est la marque du vrai génie créateur"),
    ("fr", "Qui dort en paix se réveille heureux et prêt pour demain"),
    ("fr", "La curiosité est le premier pas vers la connaissance vraie"),
    ("fr", "Ce qu'on apprend dans la jeunesse dure jusqu'à la vieillesse"),
    ("fr", "La solitude est parfois le plus beau cadeau qu'on puisse faire"),
    ("fr", "Il faut avoir les yeux ouverts pour voir la beauté du monde"),

    # ═══════════════════════════════════════════════════════
    # ITALIANO (it)
    # ═══════════════════════════════════════════════════════
    ("it", "La vita è come un'eco: restituisce quello che gli mandi"),
    ("it", "Meglio soli che male accompagnati in questo mondo incerto"),
    ("it", "Chi si ferma è perduto e chi va avanti trova la strada"),
    ("it", "L'uomo è quello che mangia ma ancor più quello che pensa"),
    ("it", "La casa è dove si trova il cuore e non dove stai il corpo"),
    ("it", "Chi non ha memoria non ha storia né futuro né identità"),
    ("it", "La vita è fatta di momenti e non di anni che scorrono via"),
    ("it", "Meglio un giorno da leone che cent'anni da pecora docile"),
    ("it", "Chi aspetta il momento perfetto non inizia mai niente"),
    ("it", "La generosità è il profumo che rimane sulla mano che dà"),
    ("it", "Non contare le ore del giorno ma fai contare ogni ora"),
    ("it", "La verità pura è raramente pura e mai completamente semplice"),
    ("it", "Chi ha coraggio abbastanza trova sempre una via d'uscita"),
    ("it", "La pazienza è una virtù che si coltiva nelle difficoltà"),
    ("it", "Non c'è niente di impossibile per chi crede davvero in sé"),
    ("it", "L'amicizia è il dono più grande che la vita ci può dare"),
    ("it", "Chi non conosce se stesso non può conoscere nessun altro"),
    ("it", "La libertà è il bene più prezioso che l'uomo possa avere"),
    ("it", "Non basta vivere bisogna anche capire il senso del vivere"),
    ("it", "Il cambiamento è la legge della vita e non si può evitarlo"),
    ("it", "Chi legge molto vive mille vite e non ne spreca nessuna"),
    ("it", "La forza vera viene da dentro e non da fuori di noi"),
    ("it", "Non si può sempre scegliere ma si può sempre scegliere come"),
    ("it", "La mente è come un fiore che sboccia quando è ben curata"),
    ("it", "Chi vuole può e chi può deve quando si tratta di aiutare"),
    ("it", "La bontà non costa nulla eppure vale moltissimo sempre"),
    ("it", "Non si tratta di dove sei ma di dove stai andando adesso"),
    ("it", "Il tempo che hai è tutto il tempo che ti serve per agire"),
    ("it", "Chi supera le sue paure trova la libertà che cercava"),
    ("it", "La speranza è come la stella polare che guida il navigante"),
    ("it", "Non c'è limite a quello che puoi fare se ci credi davvero"),
    ("it", "L'importante è partecipare con tutto se stessi ogni volta"),
    ("it", "Chi cade e si rialza è più forte di chi non è mai caduto"),
    ("it", "La musica è la lingua che parla al cuore senza parole"),
    ("it", "Non è la forza del corpo ma quella dello spirito che conta"),
    ("it", "Il successo è la somma di piccoli sforzi ripetuti nel tempo"),
    ("it", "Chi ama il proprio lavoro non lavora mai neanche un giorno"),
    ("it", "La natura è il libro più grande che sia mai stato scritto"),
    ("it", "Non si può insegnare nulla agli uomini si può solo aiutarli"),
    ("it", "Il vero viaggio di scoperta consiste nel vedere con occhi nuovi"),
    ("it", "Chi non ama non vive anche se respira e cammina ogni giorno"),
    ("it", "La saggezza è riconoscere ciò che non si sa e volerlo imparare"),
    ("it", "Non si guarda indietro per rimpiangere ma per imparare meglio"),
    ("it", "Il presente è l'unico tempo in cui si può davvero agire"),
    ("it", "Chi non sbaglia non cresce perché sbagliando si impara tutto"),
    ("it", "La grandezza non sta in ciò che si ha ma in ciò che si dà"),
    ("it", "Non c'è distanza che l'amore vero non riesca a percorrere"),
    ("it", "Il rispetto è il fondamento di ogni relazione che dura"),
    ("it", "Chi dorme non piglia pesci né gloria né fortuna alcuna"),
    ("it", "La vera libertà è scegliere come rispondere agli eventi"),
    ("it", "Non servono grandi gesti ma tanti piccoli atti d'amore"),
    ("it", "Il dubbio è il motore che spinge il pensiero in avanti"),
    ("it", "Chi impara sempre non invecchia mai davvero dentro di sé"),
    ("it", "La sconfitta è solo un'opportunità di ricominciare meglio"),
    ("it", "Non è mai troppo tardi per essere ciò che avresti potuto"),
    ("it", "Il silenzio sa dire più parole di quanto sembra all'inizio"),
    ("it", "Chi vive nel presente non ha rimpianti né paure per domani"),
    ("it", "La vita è troppo breve per essere vissuta in modo mediocre"),
    ("it", "Non cercare la felicità là fuori perché è già dentro di te"),
    ("it", "Il coraggio di amare è il coraggio di essere vulnerabile"),
    ("it", "Chi lavora sodo semina bene e raccoglie con abbondanza"),

    # ═══════════════════════════════════════════════════════
    # PORTUGUÊS (pt)
    # ═══════════════════════════════════════════════════════
    ("pt", "A vida é bela para quem sabe viver com gratidão e amor"),
    ("pt", "Quem muito dorme pouco aprende e menos ainda consegue"),
    ("pt", "Não há noite tão escura que não tenha alguma estrela"),
    ("pt", "A paciência é a virtude dos fortes e a força dos pacientes"),
    ("pt", "Quem não tem coragem para errar nunca aprende a acertar"),
    ("pt", "O amor verdadeiro não se explica apenas se sente no peito"),
    ("pt", "Não existe caminho perfeito mas há sempre um caminho melhor"),
    ("pt", "A felicidade é um estado de espírito e não uma circunstância"),
    ("pt", "Quem tem paciência tem tudo o que precisa para triunfar"),
    ("pt", "O livro abre portas que nenhuma chave do mundo consegue"),
    ("pt", "Não se aprende a nadar em terra firme há que entrar no mar"),
    ("pt", "A bondade é a linguagem que todos compreendem sem tradução"),
    ("pt", "Quem age com integridade não tem nada a temer nem a esconder"),
    ("pt", "O presente é o único tempo que temos para fazer o bem"),
    ("pt", "Não se colhe o que não se plantou nem se ganha sem esforço"),
    ("pt", "A coragem não é ausência de medo mas agir apesar dele"),
    ("pt", "Quem tem fé não teme o escuro pois leva a luz por dentro"),
    ("pt", "O silêncio às vezes é a resposta mais sábia que existe"),
    ("pt", "Não há vitória sem luta nem conquista sem determinação"),
    ("pt", "A sabedoria começa por reconhecer os próprios limites"),
    ("pt", "Quem não arrisca fica sempre no mesmo ponto da vida"),
    ("pt", "O tempo não para por ninguém e cabe a nós aproveitá-lo"),
    ("pt", "Não há erro que o tempo e a determinação não possam corrigir"),
    ("pt", "A humildade é o sinal mais seguro da verdadeira grandeza"),
    ("pt", "Quem guarda sempre encontra no momento certo e esperado"),
    ("pt", "O bom caráter vale mais do que todo o ouro do mundo"),
    ("pt", "Não se pode mudar o vento mas pode-se ajustar as velas"),
    ("pt", "A alegria do dar supera sempre a alegria do receber"),
    ("pt", "Quem caminha com os sábios torna-se sábio com o tempo"),
    ("pt", "O coração vê o que os olhos não conseguem ver nem sentir"),
    ("pt", "Não há maior riqueza do que ter uma consciência tranquila"),
    ("pt", "A verdade dita com amor nunca magoa nem faz mal algum"),
    ("pt", "Quem semeia com generosidade colhe com abundância e paz"),
    ("pt", "O mais difícil não é começar mas ter coragem de continuar"),
    ("pt", "Não se consegue o arco-íris sem primeiro passar pela chuva"),
    ("pt", "A força do caráter revela-se nas adversidades da vida"),
    ("pt", "Quem conhece os seus limites pode ir muito além deles"),
    ("pt", "O amor que une não prende e a amizade que liberta une"),
    ("pt", "Não há distância que o amor verdadeiro não consiga vencer"),
    ("pt", "A perseverança distingue os que chegam dos que desistem"),
    ("pt", "Quem vive com propósito não desperdiça nem um só dia"),
    ("pt", "O conhecimento liberta e a ignorância aprisiona sempre"),
    ("pt", "Não há maior dom do que saber reconhecer o que temos"),
    ("pt", "A generosidade é a virtude que multiplica o que se dá"),
    ("pt", "Quem respeita os outros respeita-se a si mesmo antes"),
    ("pt", "O passado é uma lição e não uma prisão para o presente"),
    ("pt", "Não se constrói uma casa em um dia nem um caráter também"),
    ("pt", "A vida premia os corajosos que não recuam perante o medo"),
    ("pt", "Quem tem bons valores tem uma bússola para toda a vida"),
    ("pt", "O mais sábio é o que sabe usar bem o que tem e conhece"),

    # ═══════════════════════════════════════════════════════
    # ESPAÑOL (es)
    # ═══════════════════════════════════════════════════════
    ("es", "El que no trabaja no come y el que no siembra no recoge"),
    ("es", "La verdad siempre sale a la luz aunque tarde mucho tiempo"),
    ("es", "Quien no conoce el amor no conoce la vida en su plenitud"),
    ("es", "No hay victoria tan grande como la que se gana sobre uno mismo"),
    ("es", "El que comienza bien tiene la mitad del trabajo ya hecho"),
    ("es", "La gratitud es el primer peldaño de la escalera del amor"),
    ("es", "Quien aprende de sus errores es dos veces más sabio"),
    ("es", "No hay mejor inversión que la que hacemos en nosotros mismos"),
    ("es", "El coraje no es no tener miedo sino actuar teniéndolo"),
    ("es", "La fortaleza del carácter se prueba en los momentos difíciles"),
    ("es", "No hay oscuridad tan densa que no pueda romperla la luz"),
    ("es", "El amor que no crece está destinado a menguar y morir"),
    ("es", "Quien vive sin ilusión vive a medias aunque respire entero"),
    ("es", "No se puede apagar el fuego con más fuego sino con agua"),
    ("es", "El que da sin esperar nada a cambio recibirá todo de vuelta"),
    ("es", "La sabiduría popular supera con creces a la erudición vana"),
    ("es", "No hay mayor pobreza que la de un espíritu sin curiosidad"),
    ("es", "El que conoce su destino puede forjarlo con sus propias manos"),
    ("es", "Quien se conoce a sí mismo conoce el mundo que le rodea"),
    ("es", "No sirve de nada correr si vamos en la dirección equivocada"),
    ("es", "El tiempo libre es el tiempo en que nos convertimos en lo que somos"),
    ("es", "La música habla donde las palabras no pueden llegar solas"),
    ("es", "No hay peor enemigo que el miedo que llevamos por dentro"),
    ("es", "El que cae y se levanta es más fuerte que el que no cayó"),
    ("es", "Quien ama su trabajo no trabaja ni un solo día de su vida"),
    ("es", "No se puede llegar al amanecer sin pasar por la noche"),
    ("es", "El cambio es la única constante en la vida de todo ser"),
    ("es", "La bondad es la única forma de riqueza que no se agota"),
    ("es", "No hay límite para quien cree en sí mismo y persevera"),
    ("es", "El hombre que domina sus propios miedos es verdaderamente libre"),
    ("es", "Quien siembra amistad cosecha compañía en los momentos duros"),
    ("es", "No se puede cambiar el viento pero sí orientar las velas"),
    ("es", "El éxito no es llegar sino el camino que se recorre para llegar"),
    ("es", "La vida premia a los valientes que no se rinden ante nada"),
    ("es", "No hay fracaso definitivo mientras haya voluntad de intentarlo"),
    ("es", "El presente es el único momento en que podemos actuar bien"),
    ("es", "Quien vive con propósito no pierde ni un solo día de su vida"),
    ("es", "No basta desear el bien hay que luchar para conseguirlo"),
    ("es", "El respeto a uno mismo es el fundamento de toda virtud"),
    ("es", "La humildad es la madre de todas las grandes virtudes humanas"),
    ("es", "No hay camino tan largo que no tenga su propio final feliz"),
    ("es", "El amor no se busca se encuentra cuando menos se espera"),
    ("es", "Quien tiene valores tiene una brújula para toda la vida"),
    ("es", "No hay herida tan grande que el tiempo no pueda sanarla"),
    ("es", "El arte de ser sabio es el arte de saber qué ignorar bien"),
    ("es", "La vida no es un ensayo general sino la función de verdad"),
    ("es", "No se puede hacer el bien a todos pero sí a quien tenemos cerca"),
    ("es", "El pasado es una fuente de aprendizaje no una prisión"),
    ("es", "Quien planta esperanza recoge confianza y amor verdadero"),
    ("es", "No hay tormenta tan fuerte que no tenga su propia calma"),
    ("es", "El que no aprende del pasado está condenado a repetirlo"),
    ("es", "La fortaleza no está en los músculos sino en la voluntad"),
    ("es", "No se puede recoger lo que no se ha sembrado con amor"),
    ("es", "El que vive bien no teme morir cuando llegue su hora"),
    ("es", "La curiosidad es el motor que impulsa todo descubrimiento"),
    ("es", "No hay lugar más seguro que los brazos del amor verdadero"),
    ("es", "El que da con alegría da dos veces sin saberlo"),
    ("es", "La perseverancia es la madre de todos los grandes logros"),
    ("es", "No hay libro tan viejo que no enseñe algo nuevo a alguien"),
    ("es", "El silencio elocuente dice más que mil palabras juntas"),
    ("es", "Quien no sueña no puede construir ni imaginar el mañana"),
    ("es", "La libertad verdadera es elegir cómo responder a la vida"),
    ("es", "No hay mayor valentía que la de ser fiel a uno mismo siempre"),
    ("es", "El que aprende a agradecer aprende a ver la belleza del mundo"),
    ("es", "La paciencia transforma las piedras en jardines con el tiempo"),
    ("es", "No se puede vivir plenamente sin amar y ser amado de verdad"),
    ("es", "El que escucha aprende y el que habla enseña a los demás"),
    ("es", "La esperanza es el ancla que nos mantiene firmes en la tormenta"),
    ("es", "No hay mayor acto de amor que respetar la libertad del otro"),
    ("es", "El que no da lo que tiene no recibe lo que necesita en la vida"),
    ("es", "La disciplina es la diferencia entre los sueños y los logros"),

    # ═══════════════════════════════════════════════════════
    # ENGLISH (en)
    # ═══════════════════════════════════════════════════════
    ("en", "The secret of success is to know something nobody else knows"),
    ("en", "Success usually comes to those who are too busy to be looking"),
    ("en", "Don't watch the clock; do what it does and keep on going"),
    ("en", "The harder the conflict the more glorious the triumph always"),
    ("en", "You miss all of the shots you never attempt to take in life"),
    ("en", "The only impossible journey is the one you never begin at all"),
    ("en", "In the end we are all just walking each other back home"),
    ("en", "Do one thing every day that scares you and you will grow"),
    ("en", "Well-behaved women seldom make history worth telling"),
    ("en", "You only live once but if you do it right once is enough"),
    ("en", "Be yourself; everyone else is already taken and has that role"),
    ("en", "A room without books is like a body without a soul inside"),
    ("en", "I have not failed; I have just found ten thousand ways that won't"),
    ("en", "The world is a book and those who do not travel read one page"),
    ("en", "You know you are in love when you cannot fall asleep because"),
    ("en", "When it rains it pours but soon the sun shines again bright"),
    ("en", "If you tell the truth you do not have to remember anything"),
    ("en", "Age is an issue of mind over matter; if you don't mind it"),
    ("en", "Wit is the lowest form of humor yet the highest form of wit"),
    ("en", "I always wanted to be somebody but now I wish I had been"),
    ("en", "To love is nothing; to be loved is something; but to love and"),
    ("en", "The difference between a stumbling block and a stepping stone"),
    ("en", "A wise man speaks because he has something to say clearly"),
    ("en", "I may not have gone where I intended but I ended up where"),
    ("en", "The best and most beautiful things cannot be seen or touched"),
    ("en", "Everything has beauty but not everyone sees it all around"),
    ("en", "Life is not measured by the breaths we take but by the moments"),
    ("en", "We cannot direct the wind but we can adjust the sails always"),
    ("en", "When you change the way you look at things the things change"),
    ("en", "What we think we become and what we become is what we do"),
    ("en", "The most courageous act is still to think for yourself aloud"),
    ("en", "There is only one way to avoid criticism: do nothing and be"),
    ("en", "The longer I live the more beautiful life becomes to my eyes"),
    ("en", "Success is not how high you have climbed but how you make"),
    ("en", "Love the life you live and live the life you love every day"),
    ("en", "You can have it all just not all at once in the same moment"),
    ("en", "The most wasted of all days is one without laughter in it"),
    ("en", "If not us who and if not now when shall we do this thing"),
    ("en", "It is better to fail in originality than succeed in imitation"),
    ("en", "The most common way people give up power is thinking they have"),
    ("en", "Imperfection is beauty madness is genius and it is better to be"),
    ("en", "If you obey all the rules you miss all the fun of the game"),
    ("en", "Keep smiling because life is a beautiful thing and there is so"),
    ("en", "You are never too old to set another goal or to dream a new"),
    ("en", "The journey of a thousand miles must begin with a single step"),
    ("en", "Perseverance is not a long race it is many short races one"),
    ("en", "Our lives begin to end the day we become silent about what matters"),
    ("en", "The greatest discovery of all time is that a person can change"),
    ("en", "If you want to go fast go alone if you want to go far go"),
    ("en", "Turn your face to the sun and the shadows fall behind you"),
    ("en", "You are confined only by the walls you build around yourself"),
    ("en", "There is no royal road to anything; one thing at a time"),
    ("en", "The expert in anything was once a beginner who did not quit"),
    ("en", "Doubt kills more dreams than failure ever will or could"),
    ("en", "Nothing is particularly hard if you divide it into small jobs"),
    ("en", "The only time you fail is the last time you try something"),
    ("en", "Remember that not getting what you want is sometimes a stroke"),
    ("en", "The biggest adventure you can take is to live the life of your"),
    ("en", "When you reach the end of your rope tie a knot and hang on"),
    ("en", "You gain strength courage and confidence by each experience"),
    ("en", "You were given this life because you are strong enough to live"),
    ("en", "Believe deep down in your heart that you are destined to do"),
    ("en", "If you can dream it you can achieve it with enough persistence"),
    ("en", "The more that you read the more things you will know and grow"),
    ("en", "Today you are you that is truer than true no one alive is"),
    ("en", "A person's a person no matter how small or how forgotten"),
    ("en", "Fantasy is a necessary ingredient in living and in dreaming"),
    ("en", "Only you can control your future by the choices you make now"),
    ("en", "You have to be odd to be number one in anything worth doing"),
    ("en", "If things start happening do not worry do not stew just go"),
    ("en", "Think left and think right and think low and think high oh"),
    ("en", "You can get help from teachers but you are going to have to"),
    ("en", "Step with care and great tact and remember that life is a"),

    # ═══════════════════════════════════════════════════════
    # ROMÂNĂ (ro) — adicionales
    # ═══════════════════════════════════════════════════════
    ("ro", "Viața e frumoasă pentru cel ce știe să o trăiască cu bucurie"),
    ("ro", "Nu se cunoaște omul la bine ci la greu când e cu adevărat"),
    ("ro", "Cine se grăbește mult ajunge puțin și obosit la capăt"),
    ("ro", "Omul harnic și cinstit ajunge departe în oricare drum"),
    ("ro", "Nu e niciodată prea târziu să fii ceea ce puteai deveni"),
    ("ro", "Binele pe care îl faci astăzi este pâinea de mâine a sufletului"),
    ("ro", "Cine nu riscă niciodată nu câștigă nimic în viața lui"),
    ("ro", "Adevărul spus cu dragoste vindecă mai repede decât orice"),
    ("ro", "Nu este bogat cel ce are mult ci cel ce are nevoie de puțin"),
    ("ro", "Omul smerit primește înțelepciune iar cel mândru rătăcește"),
    ("ro", "Fiecare zi este o nouă șansă de a deveni mai bun și mai"),
    ("ro", "Nu poți schimba vântul dar poți orienta pânzele corect"),
    ("ro", "Cel ce iubește munca lui nu muncește nicio zi din viață"),
    ("ro", "Nu există noapte atât de lungă că să nu se termine cu zori"),
    ("ro", "Omul care nu visează nu poate construi nimic trainic în viață"),
    ("ro", "Perseverența este mama tuturor reușitelor mari în viața"),
    ("ro", "Nu se poate culege ce nu s-a semănat cu grijă și dragoste"),
    ("ro", "Curajul de a începe este deja jumătate din drumul de parcurs"),
    ("ro", "Nu există obstacol atât de mare pe care voința să nu îl înfrângă"),
    ("ro", "Omul care știe să asculte învață mai mult decât cel ce vorbește"),

    # ═══════════════════════════════════════════════════════
    # CATALÀ (ca) — adicionales
    # ═══════════════════════════════════════════════════════
    ("ca", "Qui no treballa no menja i qui no menja no pot treballar bé"),
    ("ca", "La vida és bella per a qui sap viure-la amb gratitud sincera"),
    ("ca", "No hi ha victòria tan gran com la que s'aconsegueix sobre un"),
    ("ca", "Qui aprèn dels seus errors és dues vegades més savi que abans"),
    ("ca", "La curiositat és el motor que impulsa tot descobriment humà"),
    ("ca", "No es pot recollir el que no s'ha sembrat amb amor i esforç"),
    ("ca", "Qui viu amb propòsit no perd ni un sol dia de la seva vida"),
    ("ca", "La força del caràcter es revela en les adversitats de la vida"),
    ("ca", "No hi ha distància que l'amor vertader no pugui superar"),
    ("ca", "Qui coneix els seus límits pot anar molt més lluny d'ells"),
    ("ca", "La saviesa comença per reconèixer el que no se sap encara"),
    ("ca", "No es pot fer el bé a tothom però sí al que tenim a prop"),
    ("ca", "Qui planta esperança recull confiança i amor vertader"),
    ("ca", "La paciència transforma les pedres en jardins amb el temps"),
    ("ca", "No hi ha llibre tan vell que no ensenyi alguna cosa nova"),
    ("ca", "Qui no somia no pot construir ni imaginar cap demà millor"),
    ("ca", "La llibertat vertadera és triar com respondre a la vida"),
    ("ca", "No hi ha major valentia que la de ser fidel a un mateix"),
    ("ca", "Qui aprèn a agrair aprèn a veure la bellesa del món"),
    ("ca", "La disciplina és la diferència entre els somnis i els èxits"),

    # ═══════════════════════════════════════════════════════
    # GALEGO (gl) — adicionales
    # ═══════════════════════════════════════════════════════
    ("gl", "A vida é fermosa para quen sabe vivila con gratitude"),
    ("gl", "Non hai vitoria tan grande como a que se gaña sobre un mesmo"),
    ("gl", "Quen aprende dos seus erros é dúas veces máis sabio ca antes"),
    ("gl", "A curiosidade é o motor que impulsa todo descubrimento humano"),
    ("gl", "Non se pode recoller o que non se sementou con amor"),
    ("gl", "Quen vive con propósito non perde nin un día da súa vida"),
    ("gl", "A forza do carácter revélase nas adversidades da vida"),
    ("gl", "Non hai distancia que o amor verdadeiro non poida superar"),
    ("gl", "Quen coñece os seus límites pode ir moito máis alá deles"),
    ("gl", "A sabedoría comeza por recoñecer o que non se sabe aínda"),
    ("gl", "Non se pode facer o ben a todos pero si ao que temos preto"),
    ("gl", "Quen planta esperanza recolle confianza e amor verdadeiro"),
    ("gl", "A paciencia transforma as pedras en xardíns co paso do tempo"),
    ("gl", "Non hai libro tan vello que non ensine algo novo a alguén"),
    ("gl", "A liberdade verdadeira é escoller como responder á vida"),

    # ═══════════════════════════════════════════════════════
    # LATINA (la) — adicionales
    # ═══════════════════════════════════════════════════════
    ("la", "Amor est vitae essentia et sine eo vita vana est"),
    ("la", "Scientia est potentia sed sapientia est eius usus rectus"),
    ("la", "Qui tacet consentit nisi tacere debeat pro bono omnium"),
    ("la", "Vir bonus semper tiro est in arte bene vivendi"),
    ("la", "Beatus qui invenit sapientiam et obtinet prudentiam"),
    ("la", "Amicitia nisi in bonis esse non potest vera et stabilis"),
    ("la", "Dum anima est spes est et dum spes est vita est plena"),
    ("la", "Fide sed cui vidas prius antequam fidem tribuas"),
    ("la", "Intus omnia dissimilia sint frons populo nostra conveniat"),
    ("la", "Nemo mortalium omnibus horis sapit et errat interdum"),
    ("la", "Omne principium grave est sed gradatim fit facile"),
    ("la", "Patientia vincit omnia quae vis et audacia non possunt"),
    ("la", "Qui alios docet ipse discit et melior fit semper"),
    ("la", "Recede in te ipse quantum potes et eos admit qui te"),
    ("la", "Sapientia non est ingenium sed usus et experientia vitae"),

    # ═══════════════════════════════════════════════════════
    # OCCITAN (oc) — adicionales
    # ═══════════════════════════════════════════════════════
    ("oc", "La vida es bèla per aqueles que sabon viure-la amb joy"),
    ("oc", "Qui aprèn dels errors sieu es doas còps mai savi qu'abans"),
    ("oc", "La coriositat es lo motor que mena a tota descobèrta"),
    ("oc", "Non se pòt collir çò que s'es pas semnat amb amor ver"),
    ("oc", "Qui viu amb prepaus non perd una sola jornada de la vida"),
    ("oc", "La fòrça del caractèr se revèla dins las adversitats"),
    ("oc", "Non i a distància que l'amor vertadièr non posca véncer"),
    ("oc", "Qui coneis sos limits pòt anar mòlt mai luènh que creire"),
    ("oc", "La saviesa comença per reconéisser çò que hom non sap"),
    ("oc", "La paciéncia transforma las peiras en jardins amb lo temps"),
]

path = r'C:\Users\nicoa\romance_dataset.csv'
with open(path, encoding='utf-8') as f:
    existing = list(csv.DictReader(f))

existing_texts = {r['text'] for r in existing}
max_id = max(int(r['id']) for r in existing)
needed = 2000 - len(existing)
print(f"Entradas actuales: {len(existing)}, faltan: {needed}")

seen = set(existing_texts)
filtered = []
for lang, text in new_phrases:
    t = text.strip()
    if 50 <= len(t) <= 100 and t not in seen:
        seen.add(t)
        filtered.append((lang, t))

print(f"Frases nuevas válidas (50-100 chars, sin duplicados): {len(filtered)}")
final_new = filtered[:needed]
print(f"Agregando: {len(final_new)}")

all_rows = existing.copy()
for i, (lang, text) in enumerate(final_new, max_id + 1):
    all_rows.append({
        'id': i,
        'language': lang,
        'text': text,
        'text_normalized': normalize(text),
        'char_count': len(text),
    })

with open(path, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(
        f,
        fieldnames=['id', 'language', 'text', 'text_normalized', 'char_count'],
        quoting=csv.QUOTE_ALL
    )
    writer.writeheader()
    writer.writerows(all_rows)

with open(path, encoding='utf-8') as f:
    final = list(csv.DictReader(f))

lang_counts = Counter(r['language'] for r in final)
lengths = [int(r['char_count']) for r in final]
print(f"\nTotal entradas: {len(final)}")
print(f"Chars: min={min(lengths)}, max={max(lengths)}, avg={sum(lengths)/len(lengths):.1f}")
print("\nDistribucion por idioma:")
for lang, count in sorted(lang_counts.items()):
    print(f"  {lang}: {count}")
